import type { DeviceBaseInterface } from "@/types";
import { DEVICE_PROPS } from "./deviceProps";

interface DevicesInterface {
	[deviceKey: string]: DeviceBaseInterface;
}

export const DEVICES: DevicesInterface = {
	Basic_Da: {
		id: "Basic_Da",
		name: "",
		type: "device",
		size: 50,
		engName: "Basic_Da",
		props: DEVICE_PROPS.Basic_Da,
		displayOnDiagram: false,
		x: 0.1,
		y: 0.1,
		order: 1,
	},
	Lq_Tk: {
		id: "Lq_Tk",
		name: "",
		type: "device",
		size: 50,
		engName: "Lq_Tk",
		props: DEVICE_PROPS.Lq_Tk,
		displayOnDiagram: true,
		x: 0.3,
		y: 0.4,
		order: 2,
	},
	Lq_Pp: {
		id: "Lq_Pp",
		name: "",
		type: "device",
		size: 50,
		engName: "Lq_Pp",
		props: DEVICE_PROPS.Lq_Pp,
		displayOnDiagram: true,
		x: 0.4,
		y: 0.5,
		order: 3,
	},
	Lq_Vap: {
		id: "Lq_Vap",
		name: "",
		type: "device",
		size: 50,
		engName: "Lq_Vap",
		props: DEVICE_PROPS.Lq_Vap,
		displayOnDiagram: true,
		x: 0.4,
		y: 0.6,
		order: 4,
	},
	Source: {
		id: "Source",
		name: "",
		type: "device",
		size: 50,
		engName: "Source",
		props: DEVICE_PROPS.Source,
		displayOnDiagram: true,
		x: 0.4,
		y: 0.7,
		order: 5,
	},
	Buf1: {
		id: "Buf1",
		name: "",
		type: "device",
		size: 50,
		engName: "Buf1",
		props: DEVICE_PROPS.Buf1,
		displayOnDiagram: true,
		x: 0.3,
		y: 0.4,
		order: 6,
	},
	Buf2: {
		id: "Buf2",
		name: "",
		type: "device",
		size: 50,
		engName: "Buf2",
		props: DEVICE_PROPS.Buf2,
		displayOnDiagram: true,
		x: 0.4,
		y: 0.4,
		order: 7,
	},
	TT1: {
		id: "TT1",
		name: "",
		type: "device",
		size: 50,
		engName: "TT1",
		props: DEVICE_PROPS.TT1,
		displayOnDiagram: true,
		x: 0.7,
		y: 0.7,
		order: 8,
	},
	TT2: {
		id: "TT2",
		name: "",
		type: "device",
		size: 50,
		engName: "TT2",
		props: DEVICE_PROPS.TT2,
		displayOnDiagram: true,
		x: 0.6,
		y: 0.6,
		order: 9,
	},
	LCp: {
		id: "LCp",
		name: "",
		type: "device",
		size: 50,
		engName: "LCp",
		props: DEVICE_PROPS.LCp,
		displayOnDiagram: true,
		x: 0.7,
		y: 0.3,
		order: 10,
	},
	MCp1: {
		id: "MCp1",
		name: "",
		type: "device",
		size: 50,
		engName: "MCp1",
		props: DEVICE_PROPS.MCp1,
		displayOnDiagram: true,
		x: 0.6,
		y: 0.7,
		order: 11,
	},
	MCp2: {
		id: "MCp2",
		name: "",
		type: "device",
		size: 50,
		engName: "MCp2",
		props: DEVICE_PROPS.MCp2,
		displayOnDiagram: true,
		x: 0.3,
		y: 0.2,
		order: 12,
	},
	HCp: {
		id: "HCp",
		name: "",
		type: "device",
		size: 50,
		engName: "HCp",
		props: DEVICE_PROPS.HCp,
		displayOnDiagram: true,
		x: 0.9,
		y: 0.9,
		order: 13,
	},
	LBk: {
		id: "LBk",
		name: "",
		type: "device",
		size: 50,
		engName: "LBk",
		props: DEVICE_PROPS.LBk,
		displayOnDiagram: true,
		x: 0.2,
		y: 0.2,
		order: 14,
	},
	PSV_LBk: {
		id: "PSV_LBk",
		name: "",
		type: "device",
		size: 50,
		engName: "PSV_LBk",
		props: DEVICE_PROPS.PSV_LBk,
		displayOnDiagram: false,
		x: 0.1,
		y: 0.1,
		order: 15,
	},
	MBk: {
		id: "MBk",
		name: "",
		type: "device",
		size: 50,
		engName: "MBk",
		props: DEVICE_PROPS.MBk,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 16,
	},
	PSV_MBk: {
		id: "PSV_MBk",
		name: "",
		type: "device",
		size: 50,
		engName: "PSV_MBk",
		props: DEVICE_PROPS.PSV_MBk,
		displayOnDiagram: false,
		x: 0.1,
		y: 0.1,
		order: 17,
	},
	HBk: {
		id: "HBk",
		name: "",
		type: "device",
		size: 50,
		engName: "HBk",
		props: DEVICE_PROPS.HBk,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 18,
	},
	PSV_HBk: {
		id: "PSV_HBk",
		name: "",
		type: "device",
		size: 50,
		engName: "PSV_HBk",
		props: DEVICE_PROPS.PSV_HBk,
		displayOnDiagram: false,
		x: 0.1,
		y: 0.1,
		order: 19,
	},
	V130_1: {
		id: "V130_1",
		name: "",
		type: "device",
		size: 50,
		engName: "V130_1",
		props: DEVICE_PROPS.V130_1,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 20,
	},
	V140_1: {
		id: "V140_1",
		name: "",
		type: "device",
		size: 50,
		engName: "V140_1",
		props: DEVICE_PROPS.V140_1,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 21,
	},
	V150_1: {
		id: "V150_1",
		name: "",
		type: "device",
		size: 50,
		engName: "V150_1",
		props: DEVICE_PROPS.V150_1,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 22,
	},
	V130_2: {
		id: "V130_2",
		name: "",
		type: "device",
		size: 50,
		engName: "V130_2",
		props: DEVICE_PROPS.V130_2,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 23,
	},
	V140_2: {
		id: "V140_2",
		name: "",
		type: "device",
		size: 50,
		engName: "V140_2",
		props: DEVICE_PROPS.V140_2,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 24,
	},
	V150_2: {
		id: "V150_2",
		name: "",
		type: "device",
		size: 50,
		engName: "V150_2",
		props: DEVICE_PROPS.V150_2,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 25,
	},
	Disp1: {
		id: "Disp1",
		name: "",
		type: "device",
		size: 50,
		engName: "Disp1",
		props: DEVICE_PROPS.Disp1,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 26,
	},
	Disp2: {
		id: "Disp2",
		name: "",
		type: "device",
		size: 50,
		engName: "Disp2",
		props: DEVICE_PROPS.Disp2,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 27,
	},
	TkVe1: {
		id: "TkVe1",
		name: "",
		type: "device",
		size: 50,
		engName: "TkVe1",
		props: DEVICE_PROPS.TkVe1,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 28,
	},
	TkVe2: {
		id: "TkVe2",
		name: "",
		type: "device",
		size: 50,
		engName: "TkVe2",
		props: DEVICE_PROPS.TkVe2,
		displayOnDiagram: true,
		x: 0.1,
		y: 0.1,
		order: 29,
	},
	What_if: {
		id: "What_if",
		name: "",
		type: "module",
		size: 50,
		engName: "What_if",
		props: DEVICE_PROPS.What_if,
		displayOnDiagram: false,
		x: 0.1,
		y: 0.1,
		order: 30,
	},
};
