import type { DeviceBaseInterface } from "@/types";
import { DEVICE_INPUT_PROPS } from "./deviceInputProps";
import { DEVICE_OUTPUT_PROPS } from "./deviceOutputProps";

interface DevicesInterface {
  [deviceKey: string]: DeviceBaseInterface;
}

export const DEVICES: DevicesInterface = {
  Basic_Da: {
    id: "Basic_Da",
    name: "",
    type: "device",
    size: 50,
    engName: "Basic_Da",
    props: DEVICE_INPUT_PROPS.Basic_Da,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 1,
  },
  Lq_Tk: {
    id: "Lq_Tk",
    name: "",
    type: "device",
    size: 150,
    engName: "Lq_Tk",
    props: DEVICE_INPUT_PROPS.Lq_Tk,
    outputProps: DEVICE_OUTPUT_PROPS.Lq_Tk,
    displayOnDiagram: true,
    x: 0.05,
    y: 0.65,
    order: 2,
  },
  Lq_Pp: {
    id: "Lq_Pp",
    name: "",
    type: "device",
    size: 150,
    engName: "Lq_Pp",
    props: DEVICE_INPUT_PROPS.Lq_Pp,
    outputProps: DEVICE_OUTPUT_PROPS.Lq_Pp,
    displayOnDiagram: true,
    x: 0.15,
    y: 0.79,
    order: 3,
  },
  Lq_Pp2: {
    id: "Lq_Pp2",
    name: "",
    type: "device",
    size: 150,
    engName: "Lq_Pp",
    props: DEVICE_INPUT_PROPS.Lq_Pp2,
    outputProps: DEVICE_OUTPUT_PROPS.Lq_Pp2,
    displayOnDiagram: true,
    x: 0.35,
    y: 0.92,
    order: 3,
  },
  Lq_Vap: {
    id: "Lq_Vap",
    name: "",
    type: "device",
    size: 150,
    engName: "Lq_Vap",
    props: DEVICE_INPUT_PROPS.Lq_Vap,
    outputProps: DEVICE_OUTPUT_PROPS.Lq_Vap,
    displayOnDiagram: true,
    x: 0.247,
    y: 0.67,
    order: 4,
  },
  Source: {
    id: "Source",
    name: "",
    type: "device",
    size: 150,
    engName: "Source",
    props: DEVICE_INPUT_PROPS.Source,
    outputProps: DEVICE_OUTPUT_PROPS.Source,
    displayOnDiagram: true,
    x: 0.05,
    y: 0.89,
    order: 5,
  },
  Buf1: {
    id: "Buf1",
    name: "",
    type: "device",
    size: 150,
    engName: "Buf1",
    props: DEVICE_INPUT_PROPS.Buf1,
    outputProps: DEVICE_OUTPUT_PROPS.Buf1,
    displayOnDiagram: true,
    x: 0.363,
    y: 0.672,
    order: 6,
  },
  Buf2: {
    id: "Buf2",
    name: "",
    type: "device",
    size: 150,
    engName: "Buf2",
    props: DEVICE_INPUT_PROPS.Buf2,
    outputProps: DEVICE_OUTPUT_PROPS.Buf2,
    displayOnDiagram: true,
    x: 0.5,
    y: 0.92,
    order: 7,
  },
  TT1: {
    id: "TT1",
    name: "",
    type: "device",
    size: 250,
    engName: "TT1",
    props: DEVICE_INPUT_PROPS.TT1,
    outputProps: DEVICE_OUTPUT_PROPS.TT1,
    displayOnDiagram: true,
    x: 0.05,
    y: 0.34,
    order: 8,
  },
  TT2: {
    id: "TT2",
    name: "",
    type: "device",
    size: 150,
    engName: "TT2",
    props: DEVICE_INPUT_PROPS.TT2,
    outputProps: DEVICE_OUTPUT_PROPS.TT2,
    displayOnDiagram: true,
    x: 0.045,
    y: 0.05,
    order: 9,
  },
  LCp: {
    id: "LCp",
    name: "",
    type: "device",
    size: 150,
    engName: "LCp",
    props: DEVICE_INPUT_PROPS.LCp,
    outputProps: DEVICE_OUTPUT_PROPS.LCp,
    displayOnDiagram: true,
    x: 0.195,
    y: 0.35,
    order: 10,
  },
  MCp1: {
    id: "MCp1",
    name: "",
    type: "device",
    size: 150,
    engName: "MCp1",
    props: DEVICE_INPUT_PROPS.MCp1,
    outputProps: DEVICE_OUTPUT_PROPS.MCp1,
    displayOnDiagram: true,
    x: 0.456,
    y: 0.348,
    order: 11,
  },
  MCp2: {
    id: "MCp2",
    name: "",
    type: "device",
    size: 150,
    engName: "MCp2",
    props: DEVICE_INPUT_PROPS.MCp2,
    outputProps: DEVICE_OUTPUT_PROPS.MCp2,
    displayOnDiagram: true,
    x: 0.455,
    y: 0.052,
    order: 12,
  },
  HCp: {
    id: "HCp",
    name: "",
    type: "device",
    size: 150,
    engName: "HCp",
    props: DEVICE_INPUT_PROPS.HCp,
    outputProps: DEVICE_OUTPUT_PROPS.HCp,
    displayOnDiagram: true,
    x: 0.703,
    y: 0.735,
    order: 13,
  },
  LBk: {
    id: "LBk",
    name: "",
    type: "device",
    size: 150,
    engName: "LBk",
    props: DEVICE_INPUT_PROPS.LBk,
    outputProps: DEVICE_OUTPUT_PROPS.LBk,
    displayOnDiagram: true,
    x: 0.318,
    y: 0.35,
    order: 14,
  },
  PSV_LBk: {
    id: "PSV_LBk",
    name: "",
    type: "device",
    size: 50,
    engName: "PSV_LBk",
    props: DEVICE_INPUT_PROPS.PSV_LBk,
    outputProps: DEVICE_OUTPUT_PROPS.PSV_LBk,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 15,
  },
  MBk: {
    id: "MBk",
    name: "",
    type: "device",
    size: 150,
    engName: "MBk",
    props: DEVICE_INPUT_PROPS.MBk,
    outputProps: DEVICE_OUTPUT_PROPS.MBk,
    displayOnDiagram: true,
    x: 0.575,
    y: 0.35,
    order: 16,
  },
  PSV_MBk: {
    id: "PSV_MBk",
    name: "",
    type: "device",
    size: 50,
    engName: "PSV_MBk",
    props: DEVICE_INPUT_PROPS.PSV_MBk,
    outputProps: DEVICE_INPUT_PROPS.PSV_MBk,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 17,
  },
  HBk: {
    id: "HBk",
    name: "",
    type: "device",
    size: 150,
    engName: "HBk",
    props: DEVICE_INPUT_PROPS.HBk,
    outputProps: DEVICE_OUTPUT_PROPS.HBk,
    displayOnDiagram: true,
    x: 0.838,
    y: 0.74,
    order: 18,
  },
  PSV_HBk: {
    id: "PSV_HBk",
    name: "",
    type: "device",
    size: 50,
    engName: "PSV_HBk",
    props: DEVICE_INPUT_PROPS.PSV_HBk,
    outputProps: DEVICE_OUTPUT_PROPS.PSV_HBk,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 19,
  },
  V130_1: {
    id: "V130_1",
    name: "",
    type: "device",
    size: 150,
    engName: "V130_1",
    props: DEVICE_INPUT_PROPS.V130_1,
    outputProps: DEVICE_OUTPUT_PROPS.V130_1,
    displayOnDiagram: true,
    x: 0.87,
    y: 0.13,
    order: 20,
  },
  V140_1: {
    id: "V140_1",
    name: "",
    type: "device",
    size: 50,
    engName: "V140_1",
    props: DEVICE_INPUT_PROPS.V140_1,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 21,
  },
  V150_1: {
    id: "V150_1",
    name: "",
    type: "device",
    size: 50,
    engName: "V150_1",
    props: DEVICE_INPUT_PROPS.V150_1,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 22,
  },
  V130_2: {
    id: "V130_2",
    name: "",
    type: "device",
    size: 150,
    engName: "V130_2",
    props: DEVICE_INPUT_PROPS.V130_2,
    outputProps: DEVICE_OUTPUT_PROPS.V130_2,
    displayOnDiagram: true,
    x: 0.873,
    y: 0.455,
    order: 23,
  },
  V140_2: {
    id: "V140_2",
    name: "",
    type: "device",
    size: 50,
    engName: "V140_2",
    props: DEVICE_INPUT_PROPS.V140_2,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 24,
  },
  V150_2: {
    id: "V150_2",
    name: "",
    type: "device",
    size: 50,
    engName: "V150_2",
    props: DEVICE_INPUT_PROPS.V150_2,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 25,
  },
  Disp1: {
    id: "Disp1",
    name: "",
    type: "device",
    size: 150,
    engName: "Disp1",
    props: DEVICE_INPUT_PROPS.Disp1,
    outputProps: DEVICE_OUTPUT_PROPS.Disp1,
    displayOnDiagram: true,
    x: 0.8,
    y: 0.14,
    order: 26,
  },
  Disp2: {
    id: "Disp2",
    name: "",
    type: "device",
    size: 150,
    engName: "Disp2",
    props: DEVICE_INPUT_PROPS.Disp2,
    outputProps: DEVICE_OUTPUT_PROPS.Disp2,
    displayOnDiagram: true,
    x: 0.8,
    y: 0.453,
    order: 27,
  },
  TkVe1: {
    id: "TkVe1",
    name: "",
    type: "device",
    size: 150,
    engName: "TkVe1",
    props: DEVICE_INPUT_PROPS.TkVe1,
    outputProps: DEVICE_OUTPUT_PROPS.TkVe1,
    displayOnDiagram: true,
    x: 0.71,
    y: 0.13,
    order: 28,
  },
  TkVe2: {
    id: "TkVe2",
    name: "",
    type: "device",
    size: 150,
    engName: "TkVe2",
    props: DEVICE_INPUT_PROPS.TkVe2,
    outputProps: DEVICE_OUTPUT_PROPS.TkVe2,
    displayOnDiagram: true,
    x: 0.71,
    y: 0.45,
    order: 29,
  },
  What_if: {
    id: "What_if",
    name: "",
    type: "module",
    size: 50,
    engName: "What_if",
    props: DEVICE_INPUT_PROPS.What_if,
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 30,
  },
};
