import { ScenarioInterface, DevicePropertyMap } from "@/types";

const DEVICE_PROPERTIES: DevicePropertyMap = {
  device1: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device2: [
    { key: "prop1", name: "V_Tklnd2", unit: "kg" },
    { key: "prop2", name: "N_Tk2", unit: "ea" },
    { key: "prop3", name: "P_TkMax2", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin2", unit: "Mpa" },
    { key: "prop5", name: "m_sum2", unit: "kg" },
    { key: "prop6", name: "P_Tk2", unit: "Mpa" },
    { key: "prop7", name: "CP_link2", unit: "kg" },
    { key: "prop8", name: "K_link2", unit: "Mpa" },
    { key: "prop9", name: "K_comp2", unit: "op" },
    { key: "prop10", name: "Tranqw2", unit: "ss" },
  ],
  device3: [
    { key: "prop1", name: "V_Tklnd3", unit: "kg" },
    { key: "prop2", name: "N_Tk3", unit: "ea" },
    { key: "prop3", name: "P_TkMax3", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin3", unit: "Mpa" },
    { key: "prop5", name: "m_sum3", unit: "kg" },
    { key: "prop6", name: "P_Tk3", unit: "Mpa" },
    { key: "prop7", name: "CP_link3", unit: "kg" },
    { key: "prop8", name: "K_link3", unit: "Mpa" },
    { key: "prop9", name: "K_comp3", unit: "op" },
    { key: "prop10", name: "Tranqw3", unit: "ss" },
  ],
  device4: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device5: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device6: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device7: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device8: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device9: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device10: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
  device11: [
    { key: "prop1", name: "V_Tklnd", unit: "kg" },
    { key: "prop2", name: "N_Tk", unit: "ea" },
    { key: "prop3", name: "P_TkMax", unit: "Mpa" },
    { key: "prop4", name: "P_TkMin", unit: "Mpa" },
    { key: "prop5", name: "m_sum", unit: "kg" },
    { key: "prop6", name: "P_Tk", unit: "Mpa" },
    { key: "prop7", name: "CP_link", unit: "kg" },
    { key: "prop8", name: "K_link", unit: "Mpa" },
    { key: "prop9", name: "K_comp", unit: "op" },
    { key: "prop10", name: "Tranqw", unit: "ss" },
  ],
};
const SCENARIOS: ScenarioInterface[] = [
  {
    id: "SFC1012",
    name: "시나리오 SFC_1012",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram1.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1013",
    name: "시나리오 SFC_1013",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",

        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram2.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.8,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.75,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.7,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.35,
        y: 0.8,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.35,
        y: 0.85,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.35,
        y: 0.9,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.6,
        y: 0.3,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.6,
        y: 0.25,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.6,
        y: 0.2,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.88,
        y: 0.1,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.88,
        y: 0.15,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.88,
        y: 0.2,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1022",
    name: "시나리오 SFC_1022",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram3.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.1,
        y: 0.45,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.1,
        y: 0.5,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.1,
        y: 0.55,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.6,
        y: 0.3,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.6,
        y: 0.25,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.6,
        y: 0.2,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.6,
        y: 0.45,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.6,
        y: 0.5,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.6,
        y: 0.55,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.4,
        y: 0.7,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.4,
        y: 0.75,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.4,
        y: 0.8,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.4,
        y: 0.85,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1023",
    name: "시나리오 SFC_1023",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram1.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1033",
    name: "시나리오 SFC_1033",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram2.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.8,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.75,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.7,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.35,
        y: 0.8,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.35,
        y: 0.85,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.35,
        y: 0.9,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.6,
        y: 0.3,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.6,
        y: 0.25,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.6,
        y: 0.2,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.88,
        y: 0.1,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.88,
        y: 0.15,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.88,
        y: 0.2,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1232",
    name: "시나리오 SFC_1232",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram3.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input2",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input2",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC1243",
    name: "시나리오 SFC_1243",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram1.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC2012",
    name: "시나리오 SFC_2012",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram2.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.8,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.75,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.7,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.35,
        y: 0.8,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.35,
        y: 0.85,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.35,
        y: 0.9,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.6,
        y: 0.3,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.6,
        y: 0.25,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.6,
        y: 0.2,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.88,
        y: 0.1,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.88,
        y: 0.15,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.88,
        y: 0.2,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC2022",
    name: "시나리오 SFC_2022",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram3.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input2",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input2",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC2050",
    name: "시나리오 SFC_2050",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram1.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC3012",
    name: "시나리오 SFC_3012",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram2.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.8,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.75,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input3",
        x: 0.1,
        y: 0.7,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input4",
        x: 0.35,
        y: 0.8,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input5",
        x: 0.35,
        y: 0.85,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input6",
        x: 0.35,
        y: 0.9,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input7",
        x: 0.6,
        y: 0.3,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input8",
        x: 0.6,
        y: 0.25,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input9",
        x: 0.6,
        y: 0.2,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input10",
        x: 0.88,
        y: 0.1,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input11",
        x: 0.88,
        y: 0.15,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input12",
        x: 0.88,
        y: 0.2,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input13",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input14",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input15",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input16",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input17",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input18",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input19",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
  {
    id: "SFC3022",
    name: "시나리오 SFC_3022",
    type: "scenario",
    children: [
      {
        name: "TT1",
        id: "chap1",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device1,
      },
      {
        name: "MCp1",
        id: "chap2",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device2,
      },
      {
        name: "MBk",
        id: "chap3",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device3,
      },
      {
        name: "PSV_MBk",
        id: "chap4",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device4,
      },
      {
        name: "HBk",
        id: "chap5",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device5,
      },
      {
        name: "V130-1",
        id: "chap6",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device6,
      },
      {
        name: "V140-1",
        id: "chap7",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device7,
      },
      {
        name: "V150-1",
        id: "chap8",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device8,
      },
      {
        name: "V130-2",
        id: "chap9",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device9,
      },
      {
        name: "V140-2",
        id: "chap10",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device10,
      },
      {
        name: "V150-2",
        id: "chap11",
        type: "device",
        src: "",
        projectId: "",
        scenarioId: "",
        props: DEVICE_PROPERTIES.device11,
      },
    ],
    src: "diagram3.png",
    inputPoints: [
      {
        id: "input1",
        x: 0.1,
        y: 0.15,
        value: "A",
        label: "V_Tklnd",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.2,
        value: "B",
        label: "N_Tk",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.25,
        value: "C",
        label: "P_TkMax",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.3,
        value: "D",
        label: "P_TkMin(Mpa)",
        status: "error",
      },

      {
        id: "input2",
        x: 0.1,
        y: 0.45,
        value: "F",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.5,
        value: "G",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.55,
        value: "H",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.1,
        y: 0.6,
        value: "I",
        label: "m_sum(kg)",
        status: "normal",
      },

      {
        id: "input2",
        x: 0.3,
        y: 0.7,
        value: "K",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.75,
        value: "L",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.8,
        value: "M",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.3,
        y: 0.85,
        value: "N",
        label: "P_Tk(MPaa)",
        status: "warning",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.75,
        value: "O",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.8,
        value: "P",
        label: "m_sum(kg)",
        status: "error",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.85,
        value: "Q",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.7,
        y: 0.9,
        value: "R",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.5,
        value: "S",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.55,
        value: "T",
        label: "m_sum(kg)",
        status: "normal",
      },
      {
        id: "input2",
        x: 0.87,
        y: 0.6,
        value: "E",
        label: "P_Tk(MPaa)",
        status: "normal",
      },
    ],
  },
];

export { SCENARIOS };
