import { ScenarioInterface, BaseDataProps } from "@/types";
import { DEVICES } from "./devices";

const SCENARIOS: ScenarioInterface[] = [
  {
    id: "SFC1012",
    name: "시나리오 - 1012",
    sfcName: "1012",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.Lq_Tk },
      { ...DEVICES.TT1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram1.png",
  },
  {
    id: "SFC1013",
    name: "시나리오 - 1013",
    sfcName: "1013",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.LCp },
      { ...DEVICES.LBk },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram2.png",
  },
  {
    id: "SFC1022",
    name: "시나리오 - 1022",
    sfcName: "1022",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.HCp },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram3.png",
  },
  {
    id: "SFC1023",
    name: "시나리오 - 1023",
    sfcName: "1023",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.LCp },
      { ...DEVICES.MCp1 },
      { ...DEVICES.LBk },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram4.png",
  },
  {
    id: "SFC1033",
    name: "시나리오 - 1033",
    sfcName: "1033",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.LCp },
      { ...DEVICES.MCp1 },
      { ...DEVICES.HCp },
      { ...DEVICES.LBk },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram5.png",
  },
  {
    id: "SFC1232",
    name: "시나리오 - 1232",
    sfcName: "1232",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.TT2 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.MCp2 },
      { ...DEVICES.HCp },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram6.png",
  },
  {
    id: "SFC1243",
    name: "시나리오 - 1243",
    sfcName: "1243",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.TT1 },
      { ...DEVICES.TT2 },
      { ...DEVICES.LCp },
      { ...DEVICES.MCp1 },
      { ...DEVICES.MCp2 },
      { ...DEVICES.HCp },
      { ...DEVICES.LBk },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram7.png",
  },
  {
    id: "SFC2012",
    name: "시나리오 - 2012",
    sfcName: "2012",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.Lq_Tk },
      { ...DEVICES.Lq_Pp },
      { ...DEVICES.Lq_Vap },
      { ...DEVICES.Buf1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram8.png",
  },
  {
    id: "SFC2022",
    name: "시나리오 - 2022",
    sfcName: "2022",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.Lq_Tk },
      { ...DEVICES.Lq_Pp },
      { ...DEVICES.Lq_Vap },
      { ...DEVICES.Buf1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.HCp },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram9.png",
  },
  {
    id: "SFC2500",
    name: "시나리오 - 2500",
    sfcName: "2500",
    type: "scenario",
    children: [{ ...DEVICES.Basic_Da }, { ...DEVICES.Buf2 }],
    src: "diagram10.png",
  },
  {
    id: "SFC3012",
    name: "시나리오 - 3012",
    sfcName: "3012",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.Source },
      { ...DEVICES.Buf1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram11.png",
  },
  {
    id: "SFC3022",
    name: "시나리오 - 3022",
    sfcName: "3022",
    type: "scenario",
    children: [
      { ...DEVICES.Basic_Da },
      { ...DEVICES.Source },
      { ...DEVICES.Buf1 },
      { ...DEVICES.MCp1 },
      { ...DEVICES.HCp },
      { ...DEVICES.MBk },
      { ...DEVICES.HBk },
      { ...DEVICES.V130_1 },
      { ...DEVICES.V140_1 },
      { ...DEVICES.V150_1 },
      { ...DEVICES.V130_2 },
      { ...DEVICES.V140_2 },
      { ...DEVICES.V150_2 },
      { ...DEVICES.Disp1 },
      { ...DEVICES.Disp2 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.TkVe2 },
    ],
    src: "diagram12.png",
  },
  {
    id: "SFC4050",
    name: "시나리오 - 4050",
    sfcName: "4050",
    type: "scenario",
    children: [{ ...DEVICES.Disp1 }, { ...DEVICES.TkVe1 }],
    src: "diagram13.png",
  },
  {
    id: "SFC4110",
    name: "시나리오 - 4110",
    sfcName: "4110",
    type: "scenario",
    children: [{ ...DEVICES.LBk }, { ...DEVICES.PSV_LBk }],
    src: "diagram14.png",
  },
  {
    id: "SFC4120",
    name: "시나리오 - 4120",
    sfcName: "4120",
    type: "scenario",
    children: [{ ...DEVICES.MBk }, { ...DEVICES.PSV_MBk }],
    src: "diagram15.png",
  },
  {
    id: "SFC4130",
    name: "시나리오 - 4130",
    sfcName: "4130",
    type: "scenario",
    children: [{ ...DEVICES.HBk }, { ...DEVICES.PSV_HBk }],
    src: "diagram16.png",
  },
  {
    id: "SFC4500",
    name: "시나리오 - 4500",
    sfcName: "4500",
    type: "scenario",
    children: [{ ...DEVICES.Lq_Tk }],
    src: "diagram17.png",
  },
  {
    id: "SFC5110",
    name: "시나리오 - 5110",
    sfcName: "5110",
    type: "scenario",
    children: [
      { ...DEVICES.Disp1 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.What_if },
    ],
    src: "diagram18.png",
  },
];
// const SCENARIO_BASE_DATA: ScenarioBaseDataInterface[] = [
//   {
//     id: "SFC1012",
//     props: [
//       {
//         id: "prop1",
//         key: "prop1",
//         name: "대기온도",
//         altName: "(T_AmbC)",
//         unit: "℃",
//         value: "",
//         description: "",
//         type: "text",
//         placeholder: "이렇게 입력하세요...",
//       },
//       {
//         id: "prop2",
//         key: "prop2",
//         name: "HBk 초기 압력",
//         altName: "(P_HBk_0)",
//         unit: "MPa",
//         value: "",
//         description: "",
//         type: "text",
//       },
//       {
//         id: "prop3",
//         key: "prop3",
//         name: "디스펜서 2 적용 여부",
//         altName: "(D2On)",
//         unit: "",
//         value: "",
//         description: "",
//         type: "select",
//         options: [
//           { id: "1", name: "적용" },
//           { id: "2", name: "미적용" },
//         ],
//       },
//       {
//         id: "prop4",
//         key: "prop4",
//         name: "연속충전 적용 여부",
//         altName: "(ContOn)",
//         unit: "",
//         value: "",
//         description: "",
//         type: "select",
//         options: [
//           { id: "1", name: "적용" },
//           { id: "2", name: "미적용" },
//         ],
//       },
//       {
//         id: "prop5",
//         key: "prop5",
//         name: "Buffer Tk 충전 시간",
//         altName: "(t_PreRun)",
//         unit: "min",
//         value: "",
//         description: "",
//         type: "text",
//       },
//       {
//         id: "prop6",
//         key: "prop6",
//         name: "PSV 용량 계산 적용 여부",
//         altName: "(PSVOn)",
//         unit: "",
//         value: "",
//         description: "",
//         type: "select",
//         options: [
//           { id: "1", name: "적용" },
//           { id: "2", name: "미적용" },
//         ],
//       },
//       {
//         id: "prop7",
//         key: "prop7",
//         name: "시뮬레이션 시작 전 디스펜서 1 셋팅 시간",
//         altName: "(t_PreSet1)",
//         unit: "s",
//         value: "",
//         description: "",
//         type: "text",
//       },
//       {
//         id: "prop8",
//         key: "prop8",
//         name: "시뮬레이션 시작 전 디스펜서 2 셋팅 시간",
//         altName: "(t_PreSet2)",
//         unit: "s",
//         value: "",
//         description: "",
//         type: "text",
//       },
//       {
//         id: "prop9",
//         key: "prop9",
//         name: "압축기 작동 모드",
//         altName: "(CompMod)",
//         unit: "",
//         value: "",
//         description: "",
//         type: "select",
//         options: [
//           { id: "1", name: "충전스텝에 따라 가동" },
//           { id: "2", name: "뱅크압력에 따라 가동" },
//         ],
//       },
//     ],
//   },
// ];

const SCENARIO_BASE_DATA: BaseDataProps[] = [
  {
    id: "prop1",
    key: "prop1",
    name: "대기온도",
    altName: "(T_AmbC)",
    unit: "℃",
    value: "",
    description: "",
    type: "text",
    placeholder: "이렇게 입력하세요...",
  },
  {
    id: "prop2",
    key: "prop2",
    name: "HBk 초기 압력",
    altName: "(P_HBk_0)",
    unit: "MPa",
    value: "",
    description: "",
    type: "text",
  },
  {
    id: "prop3",
    key: "prop3",
    name: "디스펜서 2 적용 여부",
    altName: "(D2On)",
    unit: "",
    value: "",
    description: "",
    type: "select",
    options: [
      { id: "1", name: "적용" },
      { id: "2", name: "미적용" },
    ],
  },
  {
    id: "prop4",
    key: "prop4",
    name: "연속충전 적용 여부",
    altName: "(ContOn)",
    unit: "",
    value: "",
    description: "",
    type: "select",
    options: [
      { id: "1", name: "적용" },
      { id: "2", name: "미적용" },
    ],
  },
  {
    id: "prop5",
    key: "prop5",
    name: "Buffer Tk 충전 시간",
    altName: "(t_PreRun)",
    unit: "min",
    value: "",
    description: "",
    type: "text",
  },
  {
    id: "prop6",
    key: "prop6",
    name: "PSV 용량 계산 적용 여부",
    altName: "(PSVOn)",
    unit: "",
    value: "",
    description: "",
    type: "select",
    options: [
      { id: "1", name: "적용" },
      { id: "2", name: "미적용" },
    ],
  },
  {
    id: "prop7",
    key: "prop7",
    name: "시뮬레이션 시작 전 디스펜서 1 셋팅 시간",
    altName: "(t_PreSet1)",
    unit: "s",
    value: "",
    description: "",
    type: "text",
  },
  {
    id: "prop8",
    key: "prop8",
    name: "시뮬레이션 시작 전 디스펜서 2 셋팅 시간",
    altName: "(t_PreSet2)",
    unit: "s",
    value: "",
    description: "",
    type: "text",
  },
  {
    id: "prop9",
    key: "prop9",
    name: "압축기 작동 모드",
    altName: "(CompMod)",
    unit: "",
    value: "",
    description: "",
    type: "select",
    options: [
      { id: "1", name: "충전스텝에 따라 가동" },
      { id: "2", name: "뱅크압력에 따라 가동" },
    ],
  },
];
const KEYS = {
  PROJECT: "PROJECT",
};

export { SCENARIOS, KEYS, SCENARIO_BASE_DATA };
