import { o } from "node_modules/framer-motion/dist/types.d-Cjd591yU";
import { INPUT_PROPERTY_META } from "./inputPropertyMeta";

const applyMeta = <T extends Record<string, any>>(properties: T) => {
  Object.values(properties).forEach((property) => {
    const meta = INPUT_PROPERTY_META[property.key];
    if (!meta) return;
    if (meta.name && (!property.name || property.name === "")) {
      property.name = meta.name;
    }
    if (
      meta.description &&
      (!property.description || property.description === "")
    ) {
      property.description = meta.description;
    }
    if (meta.unit && (!property.unit || property.unit === "")) {
      property.unit = meta.unit;
    }
    if (meta.min !== undefined) {
      property.min = meta.min;
    }
    if (meta.max !== undefined) {
      property.max = meta.max;
    }
  });
  return properties;
};

const INPUT_PROPERTIES_BASE = {
  SFC: {
    key: "SFC",
    name: "",
    unit: "-",
    description: "Supply Facility Configuration",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.52,
    y: 0.2,
    order: 1,
  },
  P_LTL: {
    key: "P_LTL",
    name: "P_LTL",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 25,
  },
  T_LTL: {
    key: "T_LTL",
    name: "T_LTL",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 26,
  },
  m_LTL: {
    key: "m_LTL",
    name: "m_LTL",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 27,
  },
  LTLOn: {
    key: "LTLOn",
    name: "LTLOn",
    unit: "",
    description: "",
    io: "Input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 28,
  },
  P_GTkIn: {
    key: "P_GTkIn",
    name: "P_GTkIn",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 29,
  },
  T_GTkIn: {
    key: "T_GTkIn",
    name: "T_GTkIn",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 30,
  },
  m_GTkIn: {
    key: "m_GTkIn",
    name: "m_GTkIn",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 31,
  },
  m_LTkOut: {
    key: "m_LTkOut",
    name: "m_LTkOut",
    unit: "",
    description: "",
    io: "Input",
    type: "Input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 32,
  },
  PBUOn: {
    key: "PBUOn",
    name: "PBUOn",
    unit: "",
    description: "",
    io: "Input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 33,
  },
  SimTime: {
    key: "SimTime",
    name: "",
    unit: "-",
    description: "Simulation Time",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.52,
    y: 0.2,
    order: 1,
  },
  Q_Fire: {
    key: "Q_Fire",
    name: "",
    unit: "-",
    description: "Q Fire",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.52,
    y: 0.2,
    order: 1,
  },
  T_AmbC: {
    key: "T_AmbC",
    name: "대기온도",
    unit: "℃",
    description: "대기온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 2,
  },
  P_HBk_0: {
    key: "P_HBk_0",
    name: "고압뱅크 초기 압력",
    unit: "MPa",
    description: "HBk 초기 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 3,
  },
  D2On: {
    key: "D2On",
    name: "디스펜서 2 적용 여부",
    unit: "-",
    description: "Dispenser 2 (0)적용, (1)미적용",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "적용" },
      { id: "1", name: "미적용" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 4,
  },
  ContOn: {
    key: "ContOn",
    name: "연속충전 적용 여부",
    unit: "-",
    description: "연속충전 (0)적용, (1)미적용",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "적용" },
      { id: "1", name: "미적용" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 5,
  },
  t_PreRun: {
    key: "t_PreRun",
    name: "버퍼탱크 충전 시간",
    unit: "min",
    description: "Buffer Tk 충전시간. 이 시간 동안 모빌리티 충전은 대기",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 6,
  },
  PSVOn: {
    key: "PSVOn",
    name: "PSV 용량 계산 적용 여부",
    unit: "-",
    description: "PSV용량계산 (1)적용, (0)미적용",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "미적용" },
      { id: "1", name: "적용" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 7,
  },
  t_PreSet1: {
    key: "t_PreSet1",
    name: "시뮬레이션 전 디스펜서 1 세팅 시간",
    unit: "sec",
    description: "시뮬레이션 시작 전, Dispenser1의 Setting 시간",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 8,
  },
  t_PreSet2: {
    key: "t_PreSet2",
    name: "시뮬레이션 전 디스펜서 2 세팅 시간",
    unit: "sec",
    description: "시뮬레이션 시작 전, Dispenser2의 Setting 시간",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 9,
  },
  CompMod: {
    key: "CompMod",
    name: "압축기 작동 모드",
    unit: "-",
    description: "(1)충전스텝에 따라 Cp 가동, (2)Bk 압력에 따라 Cp 가동",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "충전스텝에 따라 Cp 가동" },
      { id: "2", name: "Bk 압력에 따라 Cp 가동" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 10,
  },
  LqTkFill: {
    key: "LqTkFill",
    name: "초기 충전율",
    unit: "%",
    description: "탱크의 초기 충전율",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.69,
    order: 11,
    contains: [1012, 2022, 2050],
  },
  D_LqTk: {
    key: "D_LqTk",
    name: "내부 직경",
    unit: "m",
    description: "탱크내경. 0을 입력하면, 직경 : 길이 = 1 : 3으로 자동계산",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.71,
    order: 12,
    contains: [1012, 2022],
  },
  V_LqTk: {
    key: "V_LqTk",
    name: "부피",
    unit: "m3",
    description: "탱크의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.73,
    order: 13,
    contains: [1012, 2022],
  },
  LqTk_Type: {
    key: "LqTk_Type",
    name: "타입",
    unit: "-",
    description: "Tk Type (1)Horizontal cylinder, (2)Vertical cylinder",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "Horizontal cylinder" },
      { id: "2", name: "Vertical cylinder" },
    ],
    displayOnDiagram: true,
    x: 0.02,
    y: 0.75,
    order: 14,
    contains: [1012, 2022],
  },
  dt_BOG: {
    key: "dt_BOG",
    name: "BOG Time Step",
    unit: "sec",
    description: "BOG Simulation 전용 SFC에서 적용하는 Time Step",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.2,
    y: 0.4,
    order: 15,
  },
  SP_LqTk_0: {
    key: "SP_LqTk_0",
    name: "초기 압력",
    unit: "MPaa",
    description: "LqTk 초기압력(포화압력, Saturation Pressure)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 16,
  },
  R_QInG: {
    key: "R_QInG",
    name: "열 전달율",
    unit: "-",
    description:
      "액상부와 내조 사이 열전달율이 1이라고 할 때, 기상부와 내조 사이 열전달율. 0과 1사이의 값을 가지게 됨",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 17,
  },
  NER: {
    key: "NER",
    name: "KGS 코드 계산값",
    unit: "%",
    description: "0을 입력하면, KGS코드에 따라 자동 계산",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 18,
  },
  Head_Type: {
    key: "Head_Type",
    name: "헤드 타입",
    unit: "-",
    description:
      "Head Type (1)Semi-Elliptical head, (2)Hemispherical head, (3)Flat head",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "Semi-Elliptical head" },
      { id: "2", name: "Hemispherical head" },
      { id: "3", name: "Flat head" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 19,
  },
  Max_iter: {
    key: "Max_iter",
    name: "lteration 최대값",
    unit: "-",
    description: "Iteration 최대값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 20,
  },
  tol: {
    key: "tol",
    name: "tol",
    unit: "-",
    description: "tol",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 21,
  },
  T_GTkOvH: {
    key: "T_GTkOvH",
    name: "기상부 오버히트 온도",
    unit: "K",
    description: "액상부 비점 대비 기상부 오버히트 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 22,
  },
  Q_hf_In: {
    key: "Q_hf_In",
    name: "Heat flux 입력값",
    unit: "kJ/m2-s",
    description:
      "내조 외면으로 들어가는 heat flux 입력값. 액상부의 경우 이것이 100%(Q_hf * 1) 액체가스로 전달되고, 기상부의 경우 R_QInG 비율 만큼(Q_hf * R_QInG)이 기체가스로 전달된다고 가정함. 이 값에 0을 입력하면 NER 기반으로 자동 계산함",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 23,
  },
  PpOn: {
    key: "PpOn",
    name: "펌프 작동 여부",
    unit: "-",
    description: "1이면 펌프 작동, 0이면 펌프 미작동",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 24,
  },
  PSVOn_LqTk: {
    key: "PSVOn_LqTk",
    name: "PSV 작동 여부",
    unit: "-",
    description: "1이면 PSV 작동, 0이면 PSV 미작동",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 25,
  },
  P_PSVSet_LqTk: {
    key: "P_PSVSet_LqTk",
    name: "분출량 결정 압력",
    unit: "MPa",
    description: "분출량결정압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 26,
  },
  m_PSVCa_LqTk: {
    key: "m_PSVCa_LqTk",
    name: "PSV 분출 용량",
    unit: "kg/h",
    description: "PSV 분출용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 27,
  },
  F_Clos_LqTk: {
    key: "F_Clos_LqTk",
    name: "Closure Start 압력",
    unit: "MPa",
    description:
      "Descending Phase에서 Closure Start하는 압력은 P_PSV_Setg x F_Closure",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 28,
  },
  F_FOp_LqTk: {
    key: "F_FOp_LqTk",
    name: "PSV Full Open 압력",
    unit: "MPa",
    description: "PSV가 Full Open 되는 압력은 P_PSV_Setg x F_FullOpen",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 29,
  },
  P_Out_LqPp: {
    key: "P_Out_LqPp",
    name: "펌프 인출 압력",
    unit: "MPa",
    description: "펌프 인출 압력(Low Pressure Pump)",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.122,
    y: 0.83,
    order: 30,
  },
  N_LqPp: {
    key: "N_LqPp",
    name: "펌프 수량",
    unit: "ea",
    description: "펌프 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.122,
    y: 0.85,
    order: 31,
  },
  P_InHH: {
    key: "P_InHH",
    name: "펌프 인입 압력 HH",
    unit: "MPa",
    description: "펌프 인입압력 HH",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 32,
  },
  P_InH: {
    key: "P_InH",
    name: "펌프 인입 압력 H",
    unit: "MPa",
    description: "펌프 인입압력 H",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 33,
  },
  T_InHH: {
    key: "T_InHH",
    name: "펌프 인입 온도 HH",
    unit: "K",
    description: "펌프 인입온도 HH",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 34,
  },
  T_InH: {
    key: "T_InH",
    name: "펌프 인입 온도 H",
    unit: "K",
    description: "펌프 인입온도 H",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 35,
  },
  Eta_LqPp: {
    key: "Eta_LqPp",
    name: "펌프 효율",
    unit: "-",
    description:
      "펌프 효율: 일반적으로 피스톤식 0.7-0.85, 터보식 0.85(소요전력 계산시 적용)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 36,
  },
  V_ref_LqPp: {
    key: "V_ref_LqPp",
    name: "실제 이송 체적",
    unit: "m3/h",
    description: "Pump 1회전당 실재 이송 체적",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 37,
  },
  Sp_Ref_LqPp: {
    key: "Sp_Ref_LqPp",
    name: "펌프 초당 회전수",
    unit: "RPS",
    description: "펌프의 초당 회전(왕복)수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 38,
  },
  eta_v_LPPp: {
    key: "eta_v_LPPp",
    name: "펌프 체적 효율성",
    unit: "-",
    description: "펌프 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 39,
  },
  P_Out_LqPp2: {
    key: "P_Out_LqPp2",
    name: "펌프 인출 압력",
    unit: "MPa",
    description: "펌프 인출 압력(Low Pressure Pump)",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.32,
    y: 0.945,
    order: 30,
  },
  N_LqPp2: {
    key: "N_LqPp2",
    name: "펌프 수량",
    unit: "ea",
    description: "펌프 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.32,
    y: 0.965,
    order: 31,
  },
  P_InHH2: {
    key: "P_InHH2",
    name: "펌프 인입 압력 HH",
    unit: "MPa",
    description: "펌프 인입압력 HH",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 32,
  },
  P_InH2: {
    key: "P_InH",
    name: "펌프 인입 압력 H",
    unit: "MPa",
    description: "펌프 인입압력 H",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 33,
  },
  T_InHH2: {
    key: "T_InHH",
    name: "펌프 인입 온도 HH",
    unit: "K",
    description: "펌프 인입온도 HH",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 34,
  },
  T_InH2: {
    key: "T_InH",
    name: "펌프 인입 온도 H",
    unit: "K",
    description: "펌프 인입온도 H",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 35,
  },
  Eta_LqPp2: {
    key: "Eta_LqPp",
    name: "펌프 효율",
    unit: "-",
    description:
      "펌프 효율: 일반적으로 피스톤식 0.7-0.85, 터보식 0.85(소요전력 계산시 적용)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 36,
  },
  V_ref_LqPp2: {
    key: "V_ref_LqPp",
    name: "실제 이송 체적",
    unit: "m3/h",
    description: "Pump 1회전당 실재 이송 체적",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 37,
  },
  Sp_Ref_LqPp2: {
    key: "Sp_Ref_LqPp",
    name: "펌프 초당 회전수",
    unit: "RPS",
    description: "펌프의 초당 회전(왕복)수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 38,
  },
  eta_v_LPPp2: {
    key: "eta_v_LPPp",
    name: "펌프 체적 효율성",
    unit: "-",
    description: "펌프 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 39,
  },
  N_Vap: {
    key: "N_Vap",
    name: "기화기 수량",
    unit: "ea",
    description: "Vaporizer 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.225,
    y: 0.71,
    order: 40,
  },
  VapElecOn: {
    key: "VapElecOn",
    name: "기화기 에너지원",
    unit: "-",
    description: "Vaporizer 에너지원 (0)대기식, (1)전기식",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "대기식" },
      { id: "1", name: "전기식" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 41,
  },
  Eta_Vap: {
    key: "Eta_Vap",
    name: "기화기 시스템 효율",
    unit: "-",
    description: "Vaporizer 시스템 효율",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 42,
  },
  HeatElecOn: {
    key: "HeatElecOn",
    name: "히터 에너지원",
    unit: "-",
    description: "Heater 에너지원 (0)대기식, (1)전기식",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "대기식" },
      { id: "1", name: "전기식" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 43,
  },
  Eta_Heat: {
    key: "Eta_Heat",
    name: "히터 시스템 효율",
    unit: "-",
    description: "Heater 시스템 효율",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 44,
  },
  T_OutVapSet: {
    key: "T_OutVapSet",
    name: "기화기 출구 온도",
    unit: "K",
    description: "Vaporizer 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 45,
  },
  T_OutHeatSet: {
    key: "T_OutHeatSet",
    name: "히터 출구 온도",
    unit: "K",
    description: "Heater 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 46,
  },
  m_VapCapa: {
    key: "m_VapCapa",
    name: "기화기 증방 용량",
    unit: "kg/h",
    description: "Vaporizer 증발용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 47,
  },
  N_Source: {
    key: "N_Source",
    name: "Source의 수량",
    unit: "ea",
    description: "Source(Electrolysis or Pipe)의 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.035,
    y: 0.928,
    order: 48,
  },
  P_Source: {
    key: "P_Source",
    name: "Source의 압력",
    unit: "MPa",
    description: "Source(Electrolysis or Pipe)의 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 49,
  },
  T_SourceC: {
    key: "T_SourceC",
    name: "Source의 온도",
    unit: "℃",
    description: "Source(Electrolysis or Pipe)의 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 50,
  },
  m_Source: {
    key: "m_Source",
    name: "Source의 유량",
    unit: "kg/h",
    description: "Source(Electrolysis or Pipe)의 유량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 51,
  },
  V_BufInd1: {
    key: "V_BufInd1",
    name: "부피",
    unit: "m3",
    description: "개별 Tank의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.724,
    order: 52,
  },
  N_Buf1: {
    key: "N_Buf1",
    name: "수량",
    unit: "ea",
    description: "Tank 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.744,
    order: 53,
  },
  P_BufMax1: {
    key: "P_BufMax1",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "Tank 최고압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.764,
    order: 54,
  },
  P_Buf_RC1: {
    key: "P_Buf_RC1",
    name: "재충전 압력",
    unit: "Mpa",
    description: "Tank Recharge Pressure",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.784,
    order: 55,
  },
  P_Buf_01: {
    key: "P_Buf_01",
    name: "초기 압력",
    unit: "MPa",
    description: "Tank 초기압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.804,
    order: 56,
  },
  P_BufMin1: {
    key: "P_BufMin1",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "Tank 최저압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.33,
    y: 0.824,
    order: 57,
  },
  d_BufInlet1: {
    key: "d_BufInlet1",
    name: "용기 입구 직경",
    unit: "m",
    description: "단위 Tank 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.33,
    y: 0.724,
    order: 58,
  },
  d_BufOutlet1: {
    key: "d_BufOutlet1",
    name: "용기 출구 직경",
    unit: "m",
    description: "단위 Tank 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.33,
    y: 0.724,
    order: 59,
  },
  Thick_Buf1: {
    key: "Thick_Buf1",
    name: "용기 동판 두께",
    unit: "m",
    description: "단위 Tank 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.33,
    y: 0.724,
    order: 60,
  },
  L_Buf1: {
    key: "L_Buf1",
    name: "용기 동판 길이",
    unit: "m",
    description: "단위 Tank 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 61,
  },
  rho_BufComp1: {
    key: "rho_BufComp1",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 62,
  },
  rho_BufLin1: {
    key: "rho_BufLin1",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 63,
  },
  k_BufComp1: {
    key: "k_BufComp1",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 64,
  },
  k_BufLin1: {
    key: "k_BufLin1",
    name: "동판 라이너 여전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 65,
  },
  Cp_BufComp1: {
    key: "Cp_BufComp1",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 66,
  },
  Cp_BufLin1: {
    key: "Cp_BufLin1",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 67,
  },
  V_BufInd2: {
    key: "V_BufInd2",
    name: "부피",
    unit: "m3",
    description: "개별 Tank의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.69,
    order: 68,
  },
  N_Buf2: {
    key: "N_Buf2",
    name: "수량",
    unit: "ea",
    description: "Tank 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.71,
    order: 69,
  },
  P_BufMax2: {
    key: "P_BufMax2",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "Tank 최고압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.73,
    order: 70,
  },
  P_Buf_RC2: {
    key: "P_Buf_RC2",
    name: "재충전 압력",
    unit: "Mpa",
    description: "Tank Recharge Pressure",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.75,
    order: 71,
  },
  P_Buf_02: {
    key: "P_Buf_02",
    name: "초기 압력",
    unit: "MPa",
    description: "Tank 초기압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.77,
    order: 72,
  },
  P_BufMin2: {
    key: "P_BufMin2",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "Tank 최저압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.47,
    y: 0.79,
    order: 73,
  },
  d_BufInlet2: {
    key: "d_BufInlet2",
    name: "용기 입구 직경",
    unit: "m",
    description: "단위 Tank 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 74,
  },
  d_BufOutlet2: {
    key: "d_BufOutlet2",
    name: "용기 출구 직경",
    unit: "m",
    description: "단위 Tank 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 75,
  },
  Thick_Buf2: {
    key: "Thick_Buf2",
    name: "용기 동판 두께",
    unit: "m",
    description: "단위 Tank 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 76,
  },
  L_Buf2: {
    key: "L_Buf2",
    name: "용기 동판 길이",
    unit: "m",
    description: "단위 Tank 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 77,
  },
  rho_BufComp2: {
    key: "rho_BufComp2",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 78,
  },
  rho_BufLin2: {
    key: "rho_BufLin2",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 79,
  },
  k_BufComp2: {
    key: "k_BufComp2",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 80,
  },
  k_BufLin2: {
    key: "k_BufLin2",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 81,
  },
  Cp_BufComp2: {
    key: "Cp_BufComp2",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 82,
  },
  Cp_BufLin2: {
    key: "Cp_BufLin2",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 83,
  },
  V_TTInd1: {
    key: "V_TTInd1",
    name: "부피",
    unit: "m3",
    description: "TT 구성 용기 1개의 체적",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.38,
    order: 84,
  },
  N_TT1: {
    key: "N_TT1",
    name: "수량",
    unit: "ea",
    description: "TT 구성 용기의 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.4,
    order: 85,
  },
  P_TTMax1: {
    key: "P_TTMax1",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "TT 내부 최고 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.42,
    order: 86,
  },
  P_TTMin1: {
    key: "P_TTMin1",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "TT 내부 최저 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.44,
    order: 87,
  },
  T_TT_0C1: {
    key: "T_TT_0C1",
    name: "내부 온도",
    unit: "℃",
    description: "T_TT_0C에 -1을 입력하면 T_Amb가 T_TT_0에 적용됨",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 88,
  },
  d_TTInlet1: {
    key: "d_TTInlet1",
    name: "용기 입구 직경",
    unit: "m",
    description: "TT 용기 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 89,
  },
  d_TTOutlet1: {
    key: "d_TTOutlet1",
    name: "용기 출구 직경",
    unit: "m",
    description: "TT 용기 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 90,
  },
  Thick_TT1: {
    key: "Thick_TT1",
    name: "용기 동판 두께",
    unit: "m",
    description: "TT 용기 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 91,
  },
  L_TT1: {
    key: "L_TT1",
    name: "용기 동판 길이",
    unit: "m",
    description: "TT 용기 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 92,
  },
  rho_TTComp1: {
    key: "rho_TTComp1",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "TT 용기 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 93,
  },
  rho_TTLin1: {
    key: "rho_TTLin1",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "TT 용기 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 94,
  },
  k_TTComp1: {
    key: "k_TTComp1",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "TT 용기 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 95,
  },
  k_TTLin1: {
    key: "k_TTLin1",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "TT 용기 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 96,
  },
  Cp_TTComp1: {
    key: "Cp_TTComp1",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "TT 용기 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 97,
  },
  Cp_TTLin1: {
    key: "Cp_TTLin1",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "TT 용기 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 98,
  },
  TTResetBe: {
    key: "TTResetBe",
    name: "TT Reset 기능",
    unit: "-",
    description: "TT Reset 기능 사용 (1)사용, (0)미사용",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "미사용" },
      { id: "1", name: "사용" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 99,
  },
  BkResetBe: {
    key: "BkResetBe",
    name: "Bank Reset 기능",
    unit: "-",
    description: "Bank Reset 기능 사용 (1)사용, (0)미사용",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "미사용" },
      { id: "1", name: "사용" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 100,
  },
  Target_NFu: {
    key: "Target_NFu",
    name: "Reset 기준 충전 대수",
    unit: "ea",
    description: "모빌리티 Target_NFu대 충전 후 TT Reset 적용",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 101,
  },
  Term_Refill: {
    key: "Term_Refill",
    name: "Bank Refill 시간",
    unit: "sec",
    description: "Bank Refill 시간",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 102,
  },
  V_TTInd2: {
    key: "V_TTInd2",
    name: "부피",
    unit: "m3",
    description: "TT 구성 용기 1개의 체적",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.085,
    order: 103,
  },
  N_TT2: {
    key: "N_TT2",
    name: "수량",
    unit: "ea",
    description: "TT 구성 용기의 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.105,
    order: 104,
  },
  P_TTMax2: {
    key: "P_TTMax2",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "TT 내부 최고 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.125,
    order: 105,
  },
  P_TTMin2: {
    key: "P_TTMin2",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "TT 내부 최저 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.02,
    y: 0.145,
    order: 106,
  },
  T_TT_0C2: {
    key: "T_TT_0C2",
    name: "내부 온도",
    unit: "℃",
    description: "T_Tk_0C에 -1을 입력하면 T_Amb가 T_Tk_0에 적용됨",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 107,
  },
  d_TTInlet2: {
    key: "d_TTInlet2",
    name: "용기 입구 직경",
    unit: "m",
    description: "TT 용기 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 108,
  },
  d_TTOutlet2: {
    key: "d_TTOutlet2",
    name: "용기 출구 직경",
    unit: "m",
    description: "TT 용기 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 109,
  },
  Thick_TT2: {
    key: "Thick_TT2",
    name: "용기 동판 두께",
    unit: "m",
    description: "TT 용기 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 110,
  },
  L_TT2: {
    key: "L_TT2",
    name: "용기 동판 길이",
    unit: "m",
    description: "TT 용기 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 111,
  },
  rho_TTComp2: {
    key: "rho_TTComp2",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "TT 용기 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 112,
  },
  rho_TTLin2: {
    key: "rho_TTLin2",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "TT 용기 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 113,
  },
  k_TTComp2: {
    key: "k_TTComp2",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "TT 용기 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 114,
  },
  k_TTLin2: {
    key: "k_TTLin2",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "TT 용기 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 115,
  },
  Cp_TTComp2: {
    key: "Cp_TTComp2",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "TT 용기 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 116,
  },
  Cp_TTLin2: {
    key: "Cp_TTLin2",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "TT 용기 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 117,
  },
  D100L: {
    key: "D100L",
    name: "Dispenser 1 Step 0",
    unit: "-",
    description: "Dispenser 1 Step 0",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.176,
    y: 0.39,
    order: 118,
  },
  D110L: {
    key: "D110L",
    name: "Dispenser 1 Step 10",
    unit: "-",
    description: "Dispenser 1 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.41,
    order: 119,
  },
  D120L: {
    key: "D120L",
    name: "Dispenser 1 Step 20",
    unit: "-",
    description: "Dispenser 1 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.43,
    order: 120,
  },
  D130L: {
    key: "D130L",
    name: "Dispenser 1 Step 30",
    unit: "-",
    description: "Dispenser 1 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.45,
    order: 121,
  },
  CpNFL: {
    key: "CpNFL",
    name: "압축기 가압 조건",
    unit: "-",
    description:
      "Comp Operation when No Fueling. 이 값이 1이면 모빌리티에 충전하는 동안 압축기에 의한 가압을 하지 않도록 작동",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.47,
    order: 122,
  },
  D200L: {
    key: "D200L",
    name: "Dispenser 2 Step 0",
    unit: "-",
    description: "Dispenser 2 Step 0",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.49,
    order: 123,
  },
  D210L: {
    key: "D210L",
    name: "Dispenser 2 Step 10",
    unit: "-",
    description: "Dispenser 2 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.51,
    order: 124,
  },
  D220L: {
    key: "D220L",
    name: "Dispenser 2 Step 20",
    unit: "-",
    description: "Dispenser 2 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.53,
    order: 125,
  },
  D230L: {
    key: "D230L",
    name: "Dispenser 2 Step 30",
    unit: "-",
    description: "Dispenser 2 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.55,
    order: 126,
  },
  S700L: {
    key: "S700L",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.57,
    order: 127,
  },
  N_LCp: {
    key: "N_LCp",
    name: "저압 압축기 수량",
    unit: "ea",
    description: "저압 압축기 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.176,
    y: 0.59,
    order: 128,
  },
  T_CpOCL: {
    key: "T_CpOCL",
    name: "압축기 출구 온도",
    unit: "℃",
    description: "저압 압축기 Cooling 미고려시 압축기 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 129,
  },
  P_CpInLimL: {
    key: "P_CpInLimL",
    name: "압축기 입입 압력 하한",
    unit: "MPa",
    description: "저압 압축기 인입 압력 하한",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 130,
  },
  P_refL: {
    key: "P_refL",
    name: "압축기 Refrence 압력",
    unit: "MPa",
    description: "저압 압축기 Refrence 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 131,
  },
  T_refCL: {
    key: "T_refCL",
    name: "압축기 Refrence 온도",
    unit: "℃",
    description: "저압 압축기 Refrence 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 132,
  },
  m_Cp_refL: {
    key: "m_Cp_refL",
    name: "압축기 Refrence 용량",
    unit: "kg/h",
    description: "저압 압축기 Refrence 용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 133,
  },
  Sp_CpL: {
    key: "Sp_CpL",
    name: "압축기 분당 Speed",
    unit: "RPM",
    description: "압축기 분당 Speed",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 134,
  },
  EtaVL: {
    key: "EtaVL",
    name: "압축기 체적 효율성",
    unit: "-",
    description: "저압 압축기 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 135,
  },
  T_CpOCLH: {
    key: "T_CpOCLH",
    name: "고압 압축기 출구 온도",
    unit: "℃",
    description: "고압 압축기 Cooling 미고려시 압축기 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 136,
  },
  P_CpInLimLH: {
    key: "P_CpInLimLH",
    name: "고압 압축기 인입 압력 하한",
    unit: "MPa",
    description: "고압 압축기 인입 압력 하한",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 137,
  },
  P_refLH: {
    key: "P_refLH",
    name: "고압 압축기 인입 압력 압력",
    unit: "MPa",
    description: "고압 압축기 Refrence 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 138,
  },
  T_refCLH: {
    key: "T_refCLH",
    name: "고압 압축기 인입 압력 온도",
    unit: "℃",
    description: "고압 압축기 Refrence 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 139,
  },
  m_Cp_refLH: {
    key: "m_Cp_refLH",
    name: "고압 압축기 인입 압력 용량",
    unit: "kg/h",
    description: "고압 압축기 Refrence 용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 140,
  },
  Sp_CpLH: {
    key: "Sp_CpLH",
    name: "고압 압축기 분당 Speed",
    unit: "RPM",
    description: "고압 분당 압축기 Speed",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 141,
  },
  EtaVLH: {
    key: "EtaVLH",
    name: "고압 압축기 체적 효율성",
    unit: "-",
    description: "고압 압축기 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 142,
  },
  Eta_CompL: {
    key: "Eta_CompL",
    name: "압축기 등엔트로피 효율",
    unit: "-",
    description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 143,
  },
  Eta_motorL: {
    key: "Eta_motorL",
    name: "압축기 전동기 효율",
    unit: "-",
    description: "전동기 효율: 보통 0.9~0.5",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 144,
  },
  T_CoolSetCL: {
    key: "T_CoolSetCL",
    name: "압축기 쿨링 목표 온도",
    unit: "℃",
    description: "쿨링 목표온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 145,
  },
  COPL: {
    key: "COPL",
    name: "압축기 성능 계수",
    unit: "-",
    description:
      "Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 146,
  },
  D100M: {
    key: "D100M",
    name: "Dispenser 1 Step 0",
    unit: "-",
    description: "Dispenser 1 Step 0",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.39,
    order: 147,
  },
  D110M: {
    key: "D110M",
    name: "Dispenser 1 Step 10",
    unit: "-",
    description: "Dispenser 1 Step 10",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.41,
    order: 148,
  },
  D120M: {
    key: "D120M",
    name: "Dispenser 1 Step 20",
    unit: "-",
    description: "Dispenser 1 Step 20",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.43,
    order: 149,
  },
  D130M: {
    key: "D130M",
    name: "Dispenser 1 Step 30",
    unit: "-",
    description: "Dispenser 1 Step 30",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.45,
    order: 150,
  },
  CpNFM: {
    key: "CpNFM",
    name: "압축기 미가압 조건",
    unit: "-",
    description:
      "Comp Operation when No Fueling. 이 값이 1이면 모빌리티에 충전하는 동안 압축기에 의한 가압을 하지 않도록 작동",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.47,
    order: 151,
  },
  D200M: {
    key: "D200M",
    name: "Dispenser 2 Step 0",
    unit: "-",
    description: "Dispenser 2 Step 0",
    io: "input",

    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.49,
    order: 152,
  },
  D210M: {
    key: "D210M",
    name: "Dispenser 2 Step 10",
    unit: "-",
    description: "Dispenser 2 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.425,
    y: 0.51,
    order: 153,
  },
  D220M: {
    key: "D220M",
    name: "Dispenser 2 Step 20",
    unit: "-",
    description: "Dispenser 2 Step 20",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.53,
    order: 154,
  },
  D230M: {
    key: "D230M",
    name: "Dispenser 2 Step 30",
    unit: "-",
    description: "Dispenser 2 Step 30",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.55,
    order: 155,
  },
  S700M: {
    key: "S700M",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "radio",
    options: [
      { id: "0", name: "on" },
      { id: "1", name: "off" },
    ],
    displayOnDiagram: true,
    x: 0.425,
    y: 0.57,
    order: 156,
  },
  N_MCp: {
    key: "N_MCp",
    name: "압축기 수량",
    unit: "ea",
    description: "압축기 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.425,
    y: 0.59,
    order: 157,
  },
  T_CpOCM: {
    key: "T_CpOCM",
    name: "압축기 출구 온도",
    unit: "℃",
    description: "압축기 Cooling 미고려시 압축기 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 158,
  },
  P_CpInLimM: {
    key: "P_CpInLimM",
    name: "압축기 인입 압력 하한",
    unit: "MPa",
    description: "압축기 인입 압력 하한",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 159,
  },
  P_refM: {
    key: "P_refM",
    name: "압축기 Refrence 압력",
    unit: "MPa",
    description: "압축기 Refrence 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 160,
  },
  T_refCM: {
    key: "T_refCM",
    name: "압축기 Refrence 온도",
    unit: "℃",
    description: "압축기 Refrence 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 161,
  },
  m_Cp_refM: {
    key: "m_Cp_refM",
    name: "압축기 Refrence 용량",
    unit: "kg/h",
    description: "압축기 Refrence 용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 162,
  },
  Sp_CpM: {
    key: "Sp_CpM",
    name: "압축기 분당 Speed",
    unit: "RPM",
    description: "압축기 분당 Speed",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 163,
  },
  EtaVM: {
    key: "EtaVM",
    name: "압축기 체적 효율성",
    unit: "-",
    description: "압축기 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 164,
  },
  Eta_CompM: {
    key: "Eta_CompM",
    name: "압축기 등엔트로피 효율",
    unit: "-",
    description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 165,
  },
  Eta_motorM: {
    key: "Eta_motorM",
    name: "압축기 전동기 효율",
    unit: "-",
    description: "전동기 효율: 보통 0.9~0.5",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 166,
  },
  T_CoolSetCM: {
    key: "T_CoolSetCM",
    name: "압축기 쿨링 목표 온도",
    unit: "℃",
    description: "쿨링 목표온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 167,
  },
  COPM: {
    key: "COPM",
    name: "압축기 성능 계수",
    unit: "-",
    description:
      "Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 168,
  },
  D100M2: {
    key: "D100M2",
    name: "Dispenser 1 Step 0",
    unit: "-",
    description: "Dispenser 1 Step 0",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.1,
    order: 169,
  },
  D110M2: {
    key: "D110M2",
    name: "Dispenser 1 Step 10",
    unit: "-",
    description: "Dispenser 1 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.12,
    order: 170,
  },
  D120M2: {
    key: "D120M2",
    name: "Dispenser 1 Step 20",
    unit: "-",
    description: "Dispenser 1 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.14,
    order: 171,
  },
  D130M2: {
    key: "D130M2",
    name: "Dispenser 1 Step 30",
    unit: "-",
    description: "Dispenser 1 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.16,
    order: 172,
  },
  S500M2: {
    key: "S500M2",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.18,
    order: 173,
  },
  D200M2: {
    key: "D200M2",
    name: "Dispenser 2 Step 0",
    unit: "-",
    description: "Dispenser 2 Step 0",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.2,
    order: 174,
  },
  D210M2: {
    key: "D210M2",
    name: "Dispenser 2 Step 10",
    unit: "-",
    description: "Dispenser 2 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.22,
    order: 175,
  },
  D220M2: {
    key: "D220M2",
    name: "Dispenser 2 Step 20",
    unit: "-",
    description: "Dispenser 2 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.24,
    order: 176,
  },
  D230M2: {
    key: "D230M2",
    name: "Dispenser 2 Step 30",
    unit: "-",
    description: "Dispenser 2 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.26,
    order: 177,
  },
  S700M2: {
    key: "S700M2",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.43,
    y: 0.28,
    order: 178,
  },
  N_MCp2: {
    key: "N_MCp2",
    name: "압축기 수량",
    unit: "ea",
    description: "압축기 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.527,
    y: 0.1,
    order: 179,
  },
  T_CpOCM2: {
    key: "T_CpOCM2",
    name: "압축기 출구 온도",
    unit: "℃",
    description: "압축기 Cooling 미고려시 압축기 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 180,
  },
  P_CpInLimM2: {
    key: "P_CpInLimM2",
    name: "압축기 인입 압력 하한",
    unit: "MPa",
    description: "압축기 인입 압력 하한",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 181,
  },
  P_refM2: {
    key: "P_refM2",
    name: "압축기 Refrence 압력",
    unit: "MPa",
    description: "압축기 Refrence 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 182,
  },
  T_refCM2: {
    key: "T_refCM2",
    name: "압축기 Refrence 온도",
    unit: "℃",
    description: "압축기 Refrence 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 183,
  },
  m_Cp_refM2: {
    key: "m_Cp_refM2",
    name: "압축기 Refrence 용량",
    unit: "kg/h",
    description: "압축기 Refrence 용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 184,
  },
  Sp_CpM2: {
    key: "Sp_CpM2",
    name: "압축기 분당 Speed",
    unit: "RPM",
    description: "압축기 분당 Speed",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 185,
  },
  EtaVM2: {
    key: "EtaVM2",
    name: "압축기 체적 효율성",
    unit: "-",
    description: "압축기 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 186,
  },
  Eta_CompM2: {
    key: "Eta_CompM2",
    name: "압축기 등엔트로피 효율",
    unit: "-",
    description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 187,
  },
  Eta_motorM2: {
    key: "Eta_motorM2",
    name: "압축기 전동기 효율",
    unit: "-",
    description: "전동기 효율: 보통 0.9~0.5",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 188,
  },
  T_CoolSetCM2: {
    key: "T_CoolSetCM2",
    name: "압축기 쿨링 목표 온도",
    unit: "℃",
    description: "쿨링 목표온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 189,
  },
  COPM2: {
    key: "COPM2",
    name: "압축기 성능 계수",
    unit: "-",
    description:
      "Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 190,
  },
  D100H: {
    key: "D100H",
    name: "Dispenser 1 Step 0",
    unit: "-",
    description: "Dispenser 1 Step 0",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.783,
    order: 191,
  },
  D110H: {
    key: "D110H",
    name: "Dispenser 1 Step 10",
    unit: "-",
    description: "Dispenser 1 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.803,
    order: 192,
  },
  D120H: {
    key: "D120H",
    name: "Dispenser 1 Step 20",
    unit: "-",
    description: "Dispenser 1 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.823,
    order: 193,
  },
  D130H: {
    key: "D130H",
    name: "Dispenser 1 Step 30",
    unit: "-",
    description: "Dispenser 1 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.843,
    order: 194,
  },
  S500H: {
    key: "S500H",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.863,
    order: 195,
  },
  D200H: {
    key: "D200H",
    name: "Dispenser 2 Step 0",
    unit: "-",
    description: "Dispenser 2 Step 0",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.883,
    order: 196,
  },
  D210H: {
    key: "D210H",
    name: "Dispenser 2 Step 10",
    unit: "-",
    description: "Dispenser 2 Step 10",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.903,
    order: 197,
  },
  D220H: {
    key: "D220H",
    name: "Dispenser 2 Step 20",
    unit: "-",
    description: "Dispenser 2 Step 20",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.923,
    order: 198,
  },
  D230H: {
    key: "D230H",
    name: "Dispenser 2 Step 30",
    unit: "-",
    description: "Dispenser 2 Step 30",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.943,
    order: 199,
  },
  S700H: {
    key: "S700H",
    name: "예비",
    unit: "-",
    description: "예비",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.963,
    order: 200,
  },
  N_HCp: {
    key: "N_HCp",
    name: "압축기 수량",
    unit: "ea",
    description: "압축기 수량",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.683,
    y: 0.983,
    order: 201,
  },
  T_CpOCH: {
    key: "T_CpOCH",
    name: "압축기 출구 온도",
    unit: "℃",
    description: "압축기 Cooling 미고려시 압축기 출구 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 202,
  },
  P_CpInLimH: {
    key: "P_CpInLimH",
    name: "압축기 인입 압력 하한",
    unit: "MPa",
    description: "압축기 인입 압력 하한",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 203,
  },
  P_refH: {
    key: "P_refH",
    name: "압축기 Refrence 압력",
    unit: "MPa",
    description: "압축기 Refrence 압력",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 204,
  },
  T_refCH: {
    key: "T_refCH",
    name: "압축기 Refrence 온도",
    unit: "℃",
    description: "압축기 Refrence 온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 205,
  },
  m_Cp_refH: {
    key: "m_Cp_refH",
    name: "압축기 Refrence 용량",
    unit: "kg/h",
    description: "압축기 Refrence 용량",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 206,
  },
  Sp_CpH: {
    key: "Sp_CpH",
    name: "압축기 분당 Speed",
    unit: "RPM",
    description: "압축기 분당 Speed",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 207,
  },
  EtaVH: {
    key: "EtaVH",
    name: "압축기 체적 효율성",
    unit: "-",
    description: "압축기 Voumetric Efficiency",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 208,
  },
  Eta_CompH: {
    key: "Eta_CompH",
    name: "압축기 등엔트로피 효율",
    unit: "-",
    description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 209,
  },
  Eta_motorH: {
    key: "Eta_motorH",
    name: "압축기 전동기 효율",
    unit: "-",
    description: "전동기 효율: 보통 0.9~0.5",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 210,
  },
  T_CoolSetCH: {
    key: "T_CoolSetCH",
    name: "압축기 쿨링 목표 온도",
    unit: "℃",
    description: "쿨링 목표온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 211,
  },
  COPH: {
    key: "COPH",
    name: "압축기 성능 계수",
    unit: "-",
    description:
      "Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 212,
  },
  V_TkIndL: {
    key: "V_TkIndL",
    name: "부피",
    unit: "m3",
    description: "개별 Tank의 부피",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.3,
    y: 0.39,
    order: 213,
  },
  N_TkL: {
    key: "N_TkL",
    name: "수량",
    unit: "ea",
    description: "탱크 개수",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.3,
    y: 0.41,
    order: 214,
  },
  P_TkMaxL: {
    key: "P_TkMaxL",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "Tank 내부 최고 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.3,
    y: 0.43,
    order: 215,
  },
  P_TkMinL: {
    key: "P_TkMinL",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "Tank 내부 최저 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.3,
    y: 0.45,
    order: 216,
  },
  FuMoOnL: {
    key: "FuMoOnL",
    name: "차압 충전 여부",
    unit: "-",
    description: "LBk에서 Vehicle에 차압충전 여부 (1)실시 (2)미실시",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "실시" },
      { id: "2", name: "미실시" },
    ],
    displayOnDiagram: true,
    x: 0.3,
    y: 0.47,
    order: 217,
  },
  T_Tk_0CL: {
    key: "T_Tk_0CL",
    name: "내부 온도",
    unit: "℃",
    description:
      "Tank 내부 초기 온도. T_Tk_0C에 -1을 입력하면 T_Amb가 T_Tk_0에 적용됨.",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 218,
  },
  d_TkInletL: {
    key: "d_TkInletL",
    name: "용기 입구 직경",
    unit: "m",
    description: "단위 Tank 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 219,
  },
  d_TkOutletL: {
    key: "d_TkOutletL",
    name: "용기 출구 직경",
    unit: "m",
    description: "단위 Tank 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 220,
  },
  Thick_TkL: {
    key: "Thick_TkL",
    name: "용기 동판 두께",
    unit: "m",
    description: "단위 Tank 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 221,
  },
  L_TkL: {
    key: "L_TkL",
    name: "용기 동판 길이",
    unit: "m",
    description: "단위 Tank 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 222,
  },
  rho_CompL: {
    key: "rho_CompL",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 223,
  },
  rho_LinL: {
    key: "rho_LinL",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 224,
  },
  k_CompL: {
    key: "k_CompL",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 225,
  },
  k_LinL: {
    key: "k_LinL",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 226,
  },
  Cp_CompL: {
    key: "Cp_CompL",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 227,
  },
  Cp_LinL: {
    key: "Cp_LinL",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 228,
  },
  KdL: {
    key: "KdL",
    name: "분출 계수",
    unit: "-",
    description: "분출계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 229,
  },
  KbL: {
    key: "KbL",
    name: "배압 보정 계수",
    unit: "-",
    description: "배압보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 230,
  },
  KcL: {
    key: "KcL",
    name: "파열판 설치 보정 계수",
    unit: "-",
    description: "파열판설치보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 231,
  },
  P_OpFullRateL: {
    key: "P_OpFullRateL",
    name: "PSV 개방개시압력 대비 완전개방압력 비율",
    unit: "-",
    description: "PSV 개방개시압력역 대비 완전개방압력 비율",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 232,
  },
  TwL: {
    key: "TwL",
    name: "탱크 표면 온도",
    unit: "K",
    description: "Tank 표면온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 233,
  },
  V_TkIndM: {
    key: "V_TkIndM",
    name: "부피",
    unit: "m3",
    description: "개별 Tank의 부피",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.545,
    y: 0.3925,
    order: 234,
  },
  N_TkM: {
    key: "N_TkM",
    name: "수량",
    unit: "ea",
    description: "탱크 개수",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.545,
    y: 0.4125,
    order: 235,
  },
  P_TkMaxM: {
    key: "P_TkMaxM",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "Tank 내부 최고 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.545,
    y: 0.4325,
    order: 236,
  },
  P_TkMinM: {
    key: "P_TkMinM",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "Tank 내부 최저 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.545,
    y: 0.4525,
    order: 237,
  },
  FuMoOnM: {
    key: "FuMoOnM",
    name: "차압 충전 여부",
    unit: "-",
    description: "MBk에서 Vehicle에 차압충전 여부 (1)실시 (2)미실시",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "실시" },
      { id: "2", name: "미실시" },
    ],
    displayOnDiagram: true,
    x: 0.545,
    y: 0.4725,
    order: 238,
  },
  T_Tk_0CM: {
    key: "T_Tk_0CM",
    name: "내부 온도",
    unit: "℃",
    description:
      "Tank 내부 초기 온도. T_Tk_0C에 -1을 입력하면 T_Amb가 T_Tk_0에 적용됨.",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 239,
  },
  d_TkInletM: {
    key: "d_TkInletM",
    name: "용기 입구 직경",
    unit: "m",
    description: "단위 Tank 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 240,
  },
  d_TkOutletM: {
    key: "d_TkOutletM",
    name: "용기 출구 직경",
    unit: "m",
    description: "단위 Tank 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 241,
  },
  Thick_TkM: {
    key: "Thick_TkM",
    name: "용기 동판 두께",
    unit: "m",
    description: "단위 Tank 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 242,
  },
  L_TkM: {
    key: "L_TkM",
    name: "용기 동판 길이",
    unit: "m",
    description: "단위 Tank 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 243,
  },
  rho_CompM: {
    key: "rho_CompM",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 244,
  },
  rho_LinM: {
    key: "rho_LinM",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 245,
  },
  k_CompM: {
    key: "k_CompM",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 246,
  },
  k_LinM: {
    key: "k_LinM",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 247,
  },
  Cp_CompM: {
    key: "Cp_CompM",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 248,
  },
  Cp_LinM: {
    key: "Cp_LinM",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 249,
  },
  KdM: {
    key: "KdM",
    name: "분출 계수",
    unit: "-",
    description: "분출계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 250,
  },
  KbM: {
    key: "KbM",
    name: "배압 보정 계수",
    unit: "-",
    description: "배압보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 251,
  },
  KcM: {
    key: "KcM",
    name: "파열판 설치 보정 계수",
    unit: "-",
    description: "파열판설치보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 252,
  },
  P_OpFullRateM: {
    key: "P_OpFullRateM",
    name: "PSV 개방개시압력 대비 완전개방압력 비율",
    unit: "-",
    description: "PSV 개방개시압력역 대비 완전개방압력 비율",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 253,
  },
  TwM: {
    key: "TwM",
    name: "탱크 표면 온도",
    unit: "K",
    description: "Tank 표면온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 254,
  },
  V_TkIndH: {
    key: "V_TkIndH",
    name: "부피",
    unit: "m3",
    description: "개별 Tank의 부피",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.81,
    y: 0.785,
    order: 255,
  },
  N_TkH: {
    key: "N_TkH",
    name: "수량",
    unit: "ea",
    description: "탱크 개수",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.81,
    y: 0.805,
    order: 256,
  },
  P_TkMaxH: {
    key: "P_TkMaxH",
    name: "내부 최고 압력",
    unit: "MPa",
    description: "Tank 내부 최고 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.81,
    y: 0.825,
    order: 257,
  },
  P_TkMinH: {
    key: "P_TkMinH",
    name: "내부 최저 압력",
    unit: "MPa",
    description: "Tank 내부 최저 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.81,
    y: 0.845,
    order: 258,
  },
  T_Tk_0CH: {
    key: "T_Tk_0CH",
    name: "내부 온도",
    unit: "℃",
    description: "Tank 내부 초기온도. 999 입력시 T_Amb로 대체됨",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 259,
  },
  d_TkInletH: {
    key: "d_TkInletH",
    name: "용기 입구 직경",
    unit: "m",
    description: "단위 Tank 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 260,
  },
  d_TkOutletH: {
    key: "d_TkOutletH",
    name: "용기 출구 직경",
    unit: "m",
    description: "단위 Tank 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 261,
  },
  Thick_TkH: {
    key: "Thick_TkH",
    name: "용기 동판 두께",
    unit: "m",
    description: "단위 Tank 동판 두께",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 262,
  },
  L_TkH: {
    key: "L_TkH",
    name: "용기 동판 길이",
    unit: "m",
    description: "단위 Tank 동판 길이",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 263,
  },
  rho_CompH: {
    key: "rho_CompH",
    name: "동판 복합재료 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 복합재료 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 264,
  },
  rho_LinH: {
    key: "rho_LinH",
    name: "동판 라이너 밀도",
    unit: "kg/m3",
    description: "단위 Tank 동판 라이너 밀도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 265,
  },
  k_CompH: {
    key: "k_CompH",
    name: "동판 복합재료 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 266,
  },
  k_LinH: {
    key: "k_LinH",
    name: "동판 라이너 열전도도",
    unit: "kW/mK",
    description: "단위 Tank 동판 라이너 열전도도(thermal conductivity) ",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 267,
  },
  Cp_CompH: {
    key: "Cp_CompH",
    name: "동판 복합재료 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 268,
  },
  Cp_LinH: {
    key: "Cp_LinH",
    name: "동판 라이너 비열",
    unit: "kJ/kg℃",
    description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 269,
  },
  KdH: {
    key: "KdH",
    name: "분출 계수",
    unit: "-",
    description: "분출계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 270,
  },
  KbH: {
    key: "KbH",
    name: "배압 보정 계수",
    unit: "-",
    description: "배압보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 271,
  },
  KcH: {
    key: "KcH",
    name: "파열판 설치 보정 계수",
    unit: "-",
    description: "파열판설치보정계수",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 272,
  },
  P_OpFullRateH: {
    key: "P_OpFullRateH",
    name: "PSV 개방개시압력 대비 완전개방압력 비율",
    unit: "-",
    description: "PSV 개방개시압력역 대비 완전개방압력 비율",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 273,
  },
  TwH: {
    key: "TwH",
    name: "탱크 표면 온도",
    unit: "K",
    description: "Tank 표면온도",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 274,
  },
  Kv1301: {
    key: "Kv1301",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 275,
  },
  d_In1301: {
    key: "d_In1301",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 276,
  },
  d_Out1301: {
    key: "d_Out1301",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 277,
  },
  Kv1401: {
    key: "Kv1401",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 278,
  },
  d_In1401: {
    key: "d_In1401",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 279,
  },
  d_Out1401: {
    key: "d_Out1401",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 280,
  },
  Kv1501: {
    key: "Kv1501",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 281,
  },
  d_In1501: {
    key: "d_In1501",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 282,
  },
  d_Out1501: {
    key: "d_Out1501",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 283,
  },
  Kv1302: {
    key: "Kv1302",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 284,
  },
  d_In1302: {
    key: "d_In1302",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 285,
  },
  d_Out1302: {
    key: "d_Out1302",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 286,
  },
  Kv1402: {
    key: "Kv1402",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 287,
  },
  d_In1402: {
    key: "d_In1402",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 288,
  },
  d_Out1402: {
    key: "d_Out1402",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 289,
  },
  Kv1502: {
    key: "Kv1502",
    name: "유량 계수",
    unit: "m³/h",
    description: "Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 290,
  },
  d_In1502: {
    key: "d_In1502",
    name: "충전라인 입구 직경",
    unit: "m",
    description: "충전라인 입구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 291,
  },
  d_Out1502: {
    key: "d_Out1502",
    name: "충전라인 출구 직경",
    unit: "m",
    description: "충전라인 출구 직경",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 292,
  },
  EA_Disp1: {
    key: "EA_Disp1",
    name: "디스펜서 개수",
    unit: "ea",
    description: "동일 종류 Dispenser 개수",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.777,
    y: 0.177,
    order: 293,
  },
  P_Class1: {
    key: "P_Class1",
    name: "충전소 압력 등급",
    unit: "MPa",
    description: "충전소 압력등급(70MPa, 35MPa 등)",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.777,
    y: 0.197,
    order: 294,
  },
  T_BaC1: {
    key: "T_BaC1",
    name: "공급 가스 온도",
    unit: "℃",
    description: "공급 가스 온도",
    io: "input",
    type: "input",
    displayOnDiagram: true,

    x: 0.777,
    y: 0.217,
    order: 295,
  },
  m_HFPLim1: {
    key: "m_HFPLim1",
    name: "충전 유량 상한",
    unit: "g/s",
    description: "충전 유량 상한",
    io: "input",
    type: "input",
    displayOnDiagram: true,

    x: 0.777,
    y: 0.237,
    order: 296,
  },
  t_BrkMax1: {
    key: "t_BrkMax1",
    name: "충전과 충전 사이의 준비 시간",
    unit: "sec",
    description: "충전과 충전 사이의 준비 시간",
    io: "input",
    type: "input",
    displayOnDiagram: true,

    x: 0.777,
    y: 0.257,
    order: 297,
  },
  HFPMode1: {
    key: "HFPMode1",
    name: "충전 프로토콜 모드",
    unit: "-",
    description: "충전프로토콜 모드",
    io: "input",
    type: "select",
    displayOnDiagram: true,

    x: 0.777,
    y: 0.277,
    order: 298,
  },
  ComOn1: {
    key: "ComOn1",
    name: "통신 방식 적용 여부",
    unit: "-",
    description: "값이 0이면 비통신 충전, 1이면 통신 충전",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "비통신충전" },
      { id: "1", name: "통신충전" },
    ],
    displayOnDiagram: true,

    x: 0.777,
    y: 0.297,
    order: 299,
  },
  Kv_Max1: {
    key: "Kv_Max1",
    name: "FCV 완전개방상태 유량",
    unit: "m³/h",
    description: "FCV 완전개방 상태의 Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 300,
  },
  dP_BkCh1: {
    key: "dP_BkCh1",
    name: "Bank Charge 실행 차압",
    unit: "MPa",
    description:
      "Bank change 실행 차압(FCV최소 입구압력보다 dP_BkCh 만큼 더 높은 압력에서 Bank change 실행)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 301,
  },
  COP1: {
    key: "COP1",
    name: "선쿨러의 성능 계수",
    unit: "-",
    description: "PreCooler의 Coefficient of Performance (1.5 - 3.5의 값)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 302,
  },
  EA_Disp2: {
    key: "EA_Disp2",
    name: "디스펜서 개수",
    unit: "ea",
    description: "동일 종류 Dispenser 개수",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.49,
    order: 303,
  },
  P_Class2: {
    key: "P_Class2",
    name: "충전소 압력 등급",
    unit: "MPa",
    description: "충전소 압력등급(70MPa, 35MPa 등)",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.51,
    order: 304,
  },
  T_BaC2: {
    key: "T_BaC2",
    name: "공급 가스 온도",
    unit: "℃",
    description: "공급 가스 온도",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.53,
    order: 305,
  },
  m_HFPLim2: {
    key: "m_HFPLim2",
    name: "충전 유량 상한",
    unit: "g/s",
    description: "충전 유량 상한",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.55,
    order: 306,
  },
  t_BrkMax2: {
    key: "t_BrkMax2",
    name: "충전과 충전 사이의 준비 시간",
    unit: "sec",
    description: "충전과 충전 사이의 준비 시간",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.57,
    order: 307,
  },
  HFPMode2: {
    key: "HFPMode2",
    name: "충전 프로토콜 모드",
    unit: "-",
    description: "충전프로토콜 모드",
    io: "input",
    type: "select",
    displayOnDiagram: true,
    x: 0.78,
    y: 0.59,
    order: 308,
  },
  ComOn2: {
    key: "ComOn2",
    name: "통신 방식 적용 여부",
    unit: "-",
    description: "값이 0이면 비통신 충전, 1이면 통신 충전",
    io: "input",
    type: "select",
    options: [
      { id: "0", name: "비통신충전" },
      { id: "1", name: "통신충전" },
    ],
    displayOnDiagram: true,
    x: 0.78,
    y: 0.61,
    order: 309,
  },
  Kv_Max2: {
    key: "Kv_Max2",
    name: "FCV 완전개방상태 유량",
    unit: "m³/h",
    description: "FCV 완전개방 상태의 Flow Coefficient (metric)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 310,
  },
  dP_BkCh2: {
    key: "dP_BkCh2",
    name: "Bank Charge 실행 차압",
    unit: "MPa",
    description:
      "Bank change 실행 차압(FCV최소 입구압력보다 dP_BkCh 만큼 더 높은 압력에서 Bank change 실행)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 311,
  },
  COP2: {
    key: "COP2",
    name: "선쿨러의 성능 계수",
    unit: "-",
    description: "PreCooler의 Coefficient of Performance (1.5 - 3.5의 값)",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 312,
  },
  V_TkMode1: {
    key: "V_TkMode1",
    name: "탱크 부피 종류",
    unit: "-",
    description: "Tank Volume의 종류. 11은 넥소, 12는 일렉시티임.",
    io: "input",
    type: "select",
    options: [
      { id: "11", name: "일렉시티" },
      { id: "12", name: "" },
      { id: "넥소", name: "" },
    ],
    displayOnDiagram: true,
    x: 0.68,
    y: 0.165,
    order: 313,
  },
  TVL1: {
    key: "TVL1",
    name: "자동차 용기 중 가장 큰 것의 부피",
    unit: "L",
    description: "자동차 용기 중 가장 큰 것의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.185,
    order: 314,
  },
  TV1: {
    key: "TV1",
    name: "자동차 용기 전체 부피",
    unit: "L",
    description: "자동차 용기 전체의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.205,
    order: 315,
  },
  P_Tk_01: {
    key: "P_Tk_01",
    name: "탱크 초기 압력",
    unit: "MPa",
    description: "Tank 초기 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.225,
    order: 316,
  },
  SOC_G1: {
    key: "SOC_G1",
    name: "SOC 목표",
    unit: "%",
    description: "Goal of SOC",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.245,
    order: 317,
  },
  T_Tk_0C1: {
    key: "T_Tk_0C1",
    name: "탱크 초기 온도",
    unit: "℃",
    description: "Tank 초기 온도. 999를 입력하면 T_Amb를 T_Tk_0로 봄.",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 318,
  },
  V_TkMode2: {
    key: "V_TkMode2",
    name: "탱크 부피 종류",
    unit: "-",
    description: "Tank Volume의 종류. 11은 넥소, 12는 일렉시티임.",
    io: "input",
    type: "select",
    options: [
      { id: "11", name: "넥소" },
      { id: "12", name: "일렉시티임." },
    ],
    displayOnDiagram: true,
    x: 0.68,
    y: 0.48,
    order: 319,
  },
  TVL2: {
    key: "TVL2",
    name: "자동차 용기 중 가장 큰 것의 부피",
    unit: "L",
    description: "자동차 용기 중 가장 큰 것의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.5,
    order: 320,
  },
  TV2: {
    key: "TV2",
    name: "자동차 용기 전체 부피",
    unit: "L",
    description: "자동차 용기 전체의 Volume",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.52,
    order: 321,
  },
  P_Tk_02: {
    key: "P_Tk_02",
    name: "탱크 초기 압력",
    unit: "MPa",
    description: "Tank 초기 압력",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.54,
    order: 322,
  },
  SOC_G2: {
    key: "SOC_G2",
    name: "SOC 목표",
    unit: "%",
    description: "Goal of SOC",
    io: "input",
    type: "input",
    displayOnDiagram: true,
    x: 0.68,
    y: 0.56,
    order: 323,
  },
  T_Tk_0C2: {
    key: "T_Tk_0C2",
    name: "탱크 초기 온도",
    unit: "℃",
    description: "Tank 초기 온도. 999를 입력하면 T_Amb를 T_Tk_0로 봄.",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 324,
  },
  N_InSelec: {
    key: "N_InSelec",
    name: "",
    unit: "-",
    description: "(1)T_AmbC+T_BaC, (2)T_AmbC+P_Tk0C, (3)T_BaC+P_Tk0C",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "T_AmbC+T_BaC" },
      { id: "2", name: "T_AmbC+P_Tk0C" },
      { id: "3", name: "T_BaC+P_Tk0C" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 325,
  },
  N_OutSelec: {
    key: "N_OutSelec",
    name: "",
    unit: "-",
    description: "(1)T_TkMax, (2)t_Elep",
    io: "input",
    type: "select",
    options: [
      { id: "1", name: "T_TkMax" },
      { id: "2", name: "t_Elep" },
    ],
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 326,
  },
  T_AmbC_Min: {
    key: "T_AmbC_Min",
    name: "",
    unit: "℃",
    description: "T_AmbC 값의 최소값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 327,
  },
  T_AmbC_Max: {
    key: "T_AmbC_Max",
    name: "",
    unit: "℃",
    description: "T_AmbC 값의 최대값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 328,
  },
  T_BaC_Min: {
    key: "T_BaC_Min",
    name: "",
    unit: "℃",
    description: "T_BaC 값의 최소값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 329,
  },
  T_BaC_Max: {
    key: "T_BaC_Max",
    name: "",
    unit: "℃",
    description: "T_BaC 값의 최대값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 330,
  },
  P_Tk0C_Min: {
    key: "P_Tk0C_Min",
    name: "",
    unit: "MPa",
    description: "P_Tk0C 값의 최소값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 331,
  },
  T_Tk0C_Max: {
    key: "T_Tk0C_Max",
    name: "",
    unit: "MPa",
    description: "P_Tk0C 값의 최대값",
    io: "input",
    type: "input",
    displayOnDiagram: false,
    x: 0.1,
    y: 0.1,
    order: 332,
  },
};

export const INPUT_PROPERTIES = applyMeta(INPUT_PROPERTIES_BASE);
