import { InputPoint } from "@/types";

import { DEVICES } from "./devices";
interface InputPointsInterface {
  [sfcName: string]: InputPoint[];
}

// export const INPUT_POINTS: InputPointsInterface = {
//   SFC1012: [
//     {
//       ...DEVICES.Basic_Da,
//       x: 0.1,
//       y: 0.1,
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1013: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.8,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.75,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.7,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.35,
//       y: 0.8,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.35,
//       y: 0.85,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.35,
//       y: 0.9,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.6,
//       y: 0.3,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.6,
//       y: 0.25,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.6,
//       y: 0.2,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.88,
//       y: 0.1,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.88,
//       y: 0.15,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.88,
//       y: 0.2,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1022: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.45,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.5,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.55,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.6,
//       y: 0.3,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.6,
//       y: 0.25,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.6,
//       y: 0.2,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.6,
//       y: 0.45,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.6,
//       y: 0.5,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.6,
//       y: 0.55,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.4,
//       y: 0.7,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.4,
//       y: 0.75,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.4,
//       y: 0.8,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.4,
//       y: 0.85,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1023: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1033: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.8,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.75,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.7,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.35,
//       y: 0.8,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.35,
//       y: 0.85,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.35,
//       y: 0.9,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.6,
//       y: 0.3,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.6,
//       y: 0.25,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.6,
//       y: 0.2,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.88,
//       y: 0.1,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.88,
//       y: 0.15,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.88,
//       y: 0.2,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1232: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc1243: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc2012: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.8,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.75,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.7,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.35,
//       y: 0.8,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.35,
//       y: 0.85,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.35,
//       y: 0.9,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.6,
//       y: 0.3,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.6,
//       y: 0.25,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.6,
//       y: 0.2,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.88,
//       y: 0.1,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.88,
//       y: 0.15,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.88,
//       y: 0.2,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc2022: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc2050: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc3012: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
//   sfc3022: [
//     {
//       id: "input1",
//       x: 0.1,
//       y: 0.15,
//       value: "A",
//       label: "V_Tklnd",
//       status: "normal",
//     },
//     {
//       id: "input2",
//       x: 0.1,
//       y: 0.2,
//       value: "B",
//       label: "N_Tk",
//       status: "normal",
//     },
//     {
//       id: "input3",
//       x: 0.1,
//       y: 0.25,
//       value: "C",
//       label: "P_TkMax",
//       status: "error",
//     },
//     {
//       id: "input4",
//       x: 0.1,
//       y: 0.3,
//       value: "D",
//       label: "P_TkMin(Mpa)",
//       status: "error",
//     },

//     {
//       id: "input5",
//       x: 0.1,
//       y: 0.45,
//       value: "F",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input6",
//       x: 0.1,
//       y: 0.5,
//       value: "G",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input7",
//       x: 0.1,
//       y: 0.55,
//       value: "H",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//     {
//       id: "input8",
//       x: 0.1,
//       y: 0.6,
//       value: "I",
//       label: "m_sum(kg)",
//       status: "normal",
//     },

//     {
//       id: "input9",
//       x: 0.3,
//       y: 0.7,
//       value: "K",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input10",
//       x: 0.3,
//       y: 0.75,
//       value: "L",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input11",
//       x: 0.3,
//       y: 0.8,
//       value: "M",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input12",
//       x: 0.3,
//       y: 0.85,
//       value: "N",
//       label: "P_Tk(MPaa)",
//       status: "warning",
//     },
//     {
//       id: "input13",
//       x: 0.7,
//       y: 0.75,
//       value: "O",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input14",
//       x: 0.7,
//       y: 0.8,
//       value: "P",
//       label: "m_sum(kg)",
//       status: "error",
//     },
//     {
//       id: "input15",
//       x: 0.7,
//       y: 0.85,
//       value: "Q",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input16",
//       x: 0.7,
//       y: 0.9,
//       value: "R",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input17",
//       x: 0.87,
//       y: 0.5,
//       value: "S",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input18",
//       x: 0.87,
//       y: 0.55,
//       value: "T",
//       label: "m_sum(kg)",
//       status: "normal",
//     },
//     {
//       id: "input19",
//       x: 0.87,
//       y: 0.6,
//       value: "E",
//       label: "P_Tk(MPaa)",
//       status: "normal",
//     },
//   ],
// };
