// Auto-generated from data.csv. Do not edit manually.
export interface InputPropertyMeta {
	name: string;
	description: string;
	unit: string;
	min?: number;
	max?: number;
}

export const INPUT_PROPERTY_META: Record<string, InputPropertyMeta> = {
	Basic_ChR: {
		name: "기본요금단가",
		description: "기본요금단가",
		unit: "kW",
		min: 0,
	},
	BkResetDo: {
		name: "Bank Reset 실행",
		description: "Bank Reset 기능 사용 (1)사용, (0)미사용",
		unit: "-",
		min: 0,
		max: 1,
	},
	COP1: {
		name: "선쿨러의 성능 계수",
		description: "PreCooler의 Coefficient of Performance (1.5 - 3.5의 값)",
		unit: "-",
	},
	COP2: {
		name: "선쿨러의 성능 계수",
		description: "PreCooler의 Coefficient of Performance (1.5 - 3.5의 값)",
		unit: "-",
	},
	COPH: {
		name: "압축기 성능 계수",
		description:
			"Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
		unit: "-",
	},
	COPL: {
		name: "압축기 성능 계수",
		description:
			"Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
		unit: "-",
	},
	COPM: {
		name: "압축기 성능 계수",
		description:
			"Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
		unit: "-",
	},
	COPM2: {
		name: "압축기 성능 계수",
		description:
			"Coefficient of Performance(성능 계수). 공랭식 2.5 - 4.0, 수냉식 4.0 - 6.0",
		unit: "-",
	},
	ComOn1: {
		name: "통신 방식 적용 여부",
		description: '값이 "0"이면 비통신 충전, "1"이면 통신 충전',
		unit: "-",
		min: 0,
		max: 1,
	},
	ComOn2: {
		name: "통신 방식 적용 여부",
		description: '값이 "0"이면 비통신 충전, "1"이면 통신 충전',
		unit: "-",
		min: 0,
		max: 1,
	},
	CompMod: {
		name: "압축기 작동 모드",
		description: "(1)충전스텝에 따라 Cp 가동, (2)Bk 압력에 따라 Cp 가동",
		unit: "-",
		min: 1,
		max: 2,
	},
	ContOn: {
		name: "연속충전 적용 여부",
		description: "연속충전 (1)적용, (0)미적용",
		unit: "-",
		min: 0,
		max: 1,
	},
	Cont_Po: {
		name: "계약 전력",
		description: "계약전력",
		unit: "kW",
		min: 0,
	},
	CpNFL: {
		name: "압축기 가압 조건",
		description:
			"Comp Operation when No Fueling. 이 값이 1이면 모빌리티에 충전하는 동안 압축기에 의한 가압을 하지 않도록 작동",
		unit: "-",
		min: 0,
		max: 1,
	},
	CpNFM: {
		name: "압축기 가가압 조건",
		description:
			"Comp Operation when No Fueling. 이 값이 1이면 모빌리티에 충전하는 동안 압축기에 의한 가압을 하지 않도록 작동",
		unit: "-",
		min: 0,
		max: 1,
	},
	Cp_BufComp1: {
		name: "동판 복합재료 비열",
		description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_BufComp2: {
		name: "동판 복합재료 비열",
		description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_BufLin1: {
		name: "동판 라이너 비열",
		description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_BufLin2: {
		name: "동판 라이너 비열",
		description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_CompH: {
		name: "동판 복합재료 비열",
		description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_CompL: {
		name: "동판 복합재료 비열",
		description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_CompM: {
		name: "동판 복합재료 비열",
		description: "단위 Tank 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_LinH: {
		name: "동판 라이너 비열",
		description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_LinL: {
		name: "동판 라이너 비열",
		description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_LinM: {
		name: "동판 라이너 비열",
		description: "단위 Tank 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_TTComp1: {
		name: "동판 복합재료 비열",
		description: "TT 용기 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_TTComp2: {
		name: "동판 복합재료 비열",
		description: "TT 용기 동판 복합재료 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_TTLin1: {
		name: "동판 라이너 비열",
		description: "TT 용기 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Cp_TTLin2: {
		name: "동판 라이너 비열",
		description: "TT 용기 동판 라이너 비열(Specific Heat Capacity)",
		unit: "kJ/kg℃",
		min: 0,
	},
	Currency_Cp: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "천$",
		min: 1,
	},
	Currency_Disp: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "백만Won",
		min: 1,
	},
	Currency_Elec: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "Won, $",
		min: 0,
		max: 1,
	},
	Currency_HBk: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "백만Won",
		min: 1,
	},
	Currency_LBk: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "백만Won",
		min: 1,
	},
	Currency_LqPp: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "$, Won",
		min: 0,
	},
	Currency_LqTk: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "$, Won",
		min: 0,
		max: 1,
	},
	Currency_Vap: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "$, Won",
		min: 0,
	},
	Currency_YrPrice: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "Won",
		min: 1,
	},
	Currency_YrPurch: {
		name: "통화 종류",
		description: "통화 종류: (1)한화 (0)미화",
		unit: "Won",
		min: 1,
	},
	D100H: {
		name: "Dispenser 1 Step 0",
		description: "Dispenser 1 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D100L: {
		name: "Dispenser 1 Step 0",
		description: "Dispenser 1 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D100M: {
		name: "Dispenser 1 Step 0",
		description: "Dispenser 1 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D100M2: {
		name: "Dispenser 1 Step 0",
		description: "Dispenser 1 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D110H: {
		name: "Dispenser 1 Step 10",
		description: "Dispenser 1 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D110L: {
		name: "Dispenser 1 Step 10",
		description: "Dispenser 1 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D110M: {
		name: "Dispenser 1 Step 10",
		description: "Dispenser 1 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D110M2: {
		name: "Dispenser 1 Step 10",
		description: "Dispenser 1 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D120H: {
		name: "Dispenser 1 Step 20",
		description: "Dispenser 1 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D120L: {
		name: "Dispenser 1 Step 20",
		description: "Dispenser 1 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D120M: {
		name: "Dispenser 1 Step 20",
		description: "Dispenser 1 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D120M2: {
		name: "Dispenser 1 Step 20",
		description: "Dispenser 1 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D130H: {
		name: "Dispenser 1 Step 30",
		description: "Dispenser 1 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D130L: {
		name: "Dispenser 1 Step 30",
		description: "Dispenser 1 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D130M: {
		name: "Dispenser 1 Step 30",
		description: "Dispenser 1 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D130M2: {
		name: "Dispenser 1 Step 30",
		description: "Dispenser 1 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D200H: {
		name: "Dispenser 2 Step 0",
		description: "Dispenser 2 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D200L: {
		name: "Dispenser 2 Step 0",
		description: "Dispenser 2 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D200M: {
		name: "Dispenser 2 Step 0",
		description: "Dispenser 2 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D200M2: {
		name: "Dispenser 2 Step 0",
		description: "Dispenser 2 Step 0",
		unit: "-",
		min: 0,
		max: 1,
	},
	D210H: {
		name: "Dispenser 2 Step 10",
		description: "Dispenser 2 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D210L: {
		name: "Dispenser 2 Step 10",
		description: "Dispenser 2 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D210M: {
		name: "Dispenser 2 Step 10",
		description: "Dispenser 2 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D210M2: {
		name: "Dispenser 2 Step 10",
		description: "Dispenser 2 Step 10",
		unit: "-",
		min: 0,
		max: 1,
	},
	D220H: {
		name: "Dispenser 2 Step 20",
		description: "Dispenser 2 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D220L: {
		name: "Dispenser 2 Step 20",
		description: "Dispenser 2 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D220M: {
		name: "Dispenser 2 Step 20",
		description: "Dispenser 2 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D220M2: {
		name: "Dispenser 2 Step 20",
		description: "Dispenser 2 Step 20",
		unit: "-",
		min: 0,
		max: 1,
	},
	D230H: {
		name: "Dispenser 2 Step 30",
		description: "Dispenser 2 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D230L: {
		name: "Dispenser 2 Step 30",
		description: "Dispenser 2 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D230M: {
		name: "Dispenser 2 Step 30",
		description: "Dispenser 2 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D230M2: {
		name: "Dispenser 2 Step 30",
		description: "Dispenser 2 Step 30",
		unit: "-",
		min: 0,
		max: 1,
	},
	D2On: {
		name: "디스펜서 2 적용 여부",
		description: "Dispenser 2 (0)적용, (1)미적용",
		unit: "-",
		min: 0,
		max: 1,
	},
	D_LqTk: {
		name: "내부 직경",
		description: '탱크내경. "0"을 입력하면, "직경 : 길이 = 1 : 3"으로 자동계산',
		unit: "m",
		min: 0,
	},
	Dal2Won: {
		name: "환율 적용",
		description: "Dallor to Won 환률",
		unit: "Won/$",
		min: 0,
	},
	EA_Disp1: {
		name: "디스펜서 개수",
		description: "동일 종류 Dispenser 개수",
		unit: "ea",
		min: 1,
	},
	EA_Disp2: {
		name: "디스펜서 개수",
		description: "동일 종류 Dispenser 개수",
		unit: "ea",
		min: 1,
	},
	EE_On: {
		name: "평가 실행 여부",
		description: "Econamic Analysis (1)On (2)Off",
		unit: ".",
		min: 0,
		max: 1,
	},
	EtaVH: {
		name: "압축기 체적 효율성",
		description: "압축기 Voumetric Efficiency",
		unit: "-",
		min: 0,
		max: 1,
	},
	EtaVL: {
		name: "압축기 체적 효율성",
		description: "저압 압축기 Voumetric Efficiency",
		unit: "-",
		min: 0,
		max: 1,
	},
	EtaVM: {
		name: "압축기 체적 효율성",
		description: "압축기 Voumetric Efficiency",
		unit: "-",
		min: 0,
		max: 1,
	},
	EtaVM2: {
		name: "압축기 체적 효율성",
		description: "압축기 Voumetric Efficiency",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_CompH: {
		name: "압축기 등엔트로피 효율",
		description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_CompL: {
		name: "압축기 등엔트로피 효율",
		description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_CompM: {
		name: "압축기 등엔트로피 효율",
		description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_CompM2: {
		name: "압축기 등엔트로피 효율",
		description: "압축기 등엔트로피효율(isentropic efficiency): 보통 0.7~0.9",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_Heat: {
		name: "히터 시스템 효율",
		description: "Heater 시스템 효율",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_LqPp: {
		name: "펌프 효율",
		description:
			"펌프 효율: 일반적으로 피스톤식 0.7-0.85, 터보식 0.85(소요전력 계산시 적용)",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_Vap: {
		name: "기화기 시스템 효율",
		description: "Vaporizer 시스템 효율",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_motorH: {
		name: "압축기 전동기 효율",
		description: "전동기 효율: 보통 0.9~0.5",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_motorL: {
		name: "압축기 전동기 효율",
		description: "전동기 효율: 보통 0.9~0.5",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_motorM: {
		name: "압축기 전동기 효율",
		description: "전동기 효율: 보통 0.9~0.5",
		unit: "-",
		min: 0,
		max: 1,
	},
	Eta_motorM2: {
		name: "압축기 전동기 효율",
		description: "전동기 효율: 보통 0.9~0.5",
		unit: "-",
		min: 0,
		max: 1,
	},
	F_Clos_LqTk: {
		name: "Closure Start 압력",
		description:
			'Descending Phase에서 Closure Start하는 압력은 "P_PSV_Setg x F_Closure"',
		unit: "-",
		min: 0,
		max: 1,
	},
	F_FOp_LqTk: {
		name: "PSV Full Open 압력",
		description: 'PSV가 Full Open 되는 압력은 "P_PSV_Setg x F_FullOpen"',
		unit: "-",
		min: 1,
	},
	F_Indi_Contingency: {
		name: "예비비 간접비용 계수",
		description: "예비비 Indirect Capital Cost Factor",
		unit: ".",
		min: 0,
	},
	F_Indi_DesignEng: {
		name: "엔지니어링 및 설계 간접비용 계수",
		description: "엔지니어링 및 설계 Indirect Capital Cost Factor",
		unit: ".",
		min: 0,
	},
	F_Indi_Licens: {
		name: "면허 간접비용 계수",
		description: "면허 Indirect Capital Cost Factor",
		unit: ".",
		min: 0,
	},
	F_Indi_Permit: {
		name: "인허가 간접비용 계수",
		description: "인허가 Indirect Capital Cost Factor",
		unit: ".",
		min: 0,
	},
	F_Indi_SitePrep: {
		name: "부지 마련 간접비용 계수",
		description: "부지 마련 Indirect Capital Cost Factor",
		unit: ".",
		min: 0,
	},
	F_Inst_Bank: {
		name: "뱅크 구매비용 대비 설치비용 계수",
		description: "Bank 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_Comp: {
		name: "압축기 구매비용 대비 설치비용 계수",
		description: "Commpreser 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_Disp: {
		name: "충전기 구매비용 대비 설치비용 계수",
		description: "Dispenser 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_Elec: {
		name: "전력 설비 구매비용 대비 설치비용 계수",
		description: "전략설비 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_LqPp: {
		name: "액화 수소 펌프 구매비용 대비 설치비용 계수",
		description: "Lq Pump 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_LqTk: {
		name: "액화 수소 탱크 구매비용 대비 설치비용 계수",
		description: "Lq Tank 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Inst_LqVap: {
		name: "액화 수소 기화기 구매비용 대비 설치비용 계수",
		description: "Lq Vaporizer 구매비용 대비 설치비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_Insurance: {
		name: "CAPEX 대비 보험 비용 계수",
		description: "CAPEX 대비 보험 비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_LicenPermit: {
		name: "CAPEX 대비 인허가.면허 비용 계수",
		description: "CAPEX 대비 인허가.면허 비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_OpexBk: {
		name: "총설치비용 대비 뱅크 유지관리 비용 계수",
		description: "총설치비용 대비 Bank 유지관리 비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_OpexComp: {
		name: "총설치비용 대비 압축기 유지관리 비용 계수",
		description: "총설치비용 대비 압축기 유지관리 비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_OpexDisp: {
		name: "총설치비용 대비 충전기 유지관리 비용 계수",
		description: "총설치비용 대비 Dispenser 유지관리 비용 계수",
		unit: ".",
		min: 0,
	},
	F_Opx_PropertyTax: {
		name: "CAPEX 대비 재산세 비용 계수",
		description: "CAPEX 대비 재산세 비용 계수",
		unit: ".",
		min: 0,
	},
	FuDayPerYr: {
		name: "연간 가동 일수",
		description: "annual operating date",
		unit: "day",
		min: 0,
		max: 365,
	},
	FuHrPerDay: {
		name: "일일 가동 시간",
		description: "daily operating hours",
		unit: "hr",
		min: 0,
	},
	FuMoOnL: {
		name: "차압 충전 여부",
		description: "LBk에서 Vehicle에 차압충전 여부 (1)실시 (2)미실시",
		unit: "-",
		min: 0,
		max: 1,
	},
	FuMoOnM: {
		name: "차압 충전 여부",
		description: "MBk에서 Vehicle에 차압충전 여부 (1)실시 (2)미실시",
		unit: "-",
		min: 0,
		max: 1,
	},
	GraphOn: {
		name: "그래프 출력 여부",
		description: "(0)Graph 미출력, (1)Graph 출력",
		unit: ".",
	},
	HFPMode1: {
		name: "충전 프로토콜 모드",
		description: "충전프로토콜 모드",
		unit: "-",
		min: 1,
		max: 3,
	},
	HFPMode2: {
		name: "충전 프로토콜 모드",
		description: "충전프로토콜 모드",
		unit: "-",
		min: 1,
		max: 3,
	},
	Head_Type: {
		name: "헤드 타입",
		description:
			"Head Type (1)Semi-Elliptical head, (2)Hemispherical head, (3)Flat head",
		unit: "-",
		min: 1,
		max: 2,
	},
	HeatElecOn: {
		name: "히터 에너지원",
		description: "Heater 에너지원 (0)대기식, (1)전기식",
		unit: "-",
		min: 0,
		max: 1,
	},
	KbH: {
		name: "배압 보정 계수",
		description: "배압보정계수",
		unit: "-",
	},
	KbL: {
		name: "배압 보정 계수",
		description: "배압보정계수",
		unit: "-",
	},
	KbM: {
		name: "배압 보정 계수",
		description: "배압보정계수",
		unit: "-",
	},
	KcH: {
		name: "파열판 설치 보정 계수",
		description: "파열판설치보정계수",
		unit: "-",
	},
	KcL: {
		name: "파열판 설치 보정 계수",
		description: "파열판설치보정계수",
		unit: "-",
	},
	KcM: {
		name: "파열판 설치 보정 계수",
		description: "파열판설치보정계수",
		unit: "-",
	},
	KdH: {
		name: "분출 계수",
		description: "분출계수",
		unit: "-",
	},
	KdL: {
		name: "분출 계수",
		description: "분출계수",
		unit: "-",
	},
	KdM: {
		name: "분출 계수",
		description: "분출계수",
		unit: "-",
	},
	Kv1301: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv1302: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv1401: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv1402: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv1501: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv1502: {
		name: "유량 계수",
		description: "Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv_Max1: {
		name: "FCV 완전개방상태 유량",
		description: "FCV 완전개방 상태의 Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	Kv_Max2: {
		name: "FCV 완전개방상태 유량",
		description: "FCV 완전개방 상태의 Flow Coefficient (metric)",
		unit: "m³/h",
		min: 0,
	},
	LTLOn: {
		name: "LTLOn",
		description: "",
		unit: "",
	},
	L_Buf1: {
		name: "용기 동판 길이",
		description: "단위 Tank 동판 길이",
		unit: "m",
		min: 0,
	},
	L_Buf2: {
		name: "용기 동판 길이",
		description: "단위 Tank 동판 길이",
		unit: "m",
		min: 0,
	},
	L_TT1: {
		name: "용기 동판 길이",
		description: "TT 용기 동판 길이",
		unit: "m",
		min: 0,
	},
	L_TT2: {
		name: "용기 동판 길이",
		description: "TT 용기 동판 길이",
		unit: "m",
		min: 0,
	},
	L_TkH: {
		name: "용기 동판 길이",
		description: "단위 Tank 동판 길이",
		unit: "m",
		min: 0,
	},
	L_TkL: {
		name: "용기 동판 길이",
		description: "단위 Tank 동판 길이",
		unit: "m",
		min: 0,
	},
	L_TkM: {
		name: "용기 동판 길이",
		description: "단위 Tank 동판 길이",
		unit: "m",
		min: 0,
	},
	LqTkFill: {
		name: "초기 충전율",
		description: "탱크의 초기 충전율",
		unit: "%",
		min: 0,
		max: 100,
	},
	LqTk_Type: {
		name: "타입",
		description: "Tk Type (1)Horizontal cylinder, (2)Vertical cylinder",
		unit: "-",
		min: 1,
		max: 2,
	},
	M_1FuHDV: {
		name: "대형 차량에 충전되는 H2 질량",
		description: "Heavy Duty Vehicle에 충전되는 H2 질량",
		unit: "kg/ea",
		min: 0,
	},
	M_2FuLDV: {
		name: "소형 차량에 충전되는 H2 질량",
		description: "Light Duty Vehicle에 충전되는 H2 질량",
		unit: "kg/ea",
		min: 0,
	},
	MaxIter: {
		name: "MaxIter",
		description: "",
		unit: "",
	},
	Max_iter: {
		name: "lteration 최대값",
		description: "Iteration 최대값",
		unit: "-",
		min: 0,
	},
	MinPer1Fu: {
		name: "수소차량 1대 충전에 소요되는 인력투입 시간",
		description: "Mobility 1대 충전에 소요되는 인력투입 시간",
		unit: "min",
		min: 0,
	},
	NER: {
		name: "KGS 코드 계산값",
		description: "0을 입력하면, KGS코드에 따라 자동 계산",
		unit: "%",
		min: 0,
	},
	N_Buf1: {
		name: "수량",
		description: "Tank 수량",
		unit: "ea",
		min: 1,
	},
	N_Buf2: {
		name: "수량",
		description: "Tank 수량",
		unit: "ea",
		min: 1,
	},
	N_FuHDV_0: {
		name: "개업 시점 대형 차량 1일 충전 대수",
		description: "HRS 개업 시점 Heavy Duty Vehicle 1일 충전 대수",
		unit: "ea/day",
		min: 0,
	},
	N_FuLDV_0: {
		name: "개업 시점 소형 차량 1일 충전 대수",
		description: "HRS 개업 시점 Light Duty Vehicle 1일 충전 대수",
		unit: "ea/day",
		min: 0,
	},
	N_HCp: {
		name: "압축기 수량",
		description: "압축기 수량",
		unit: "ea",
		min: 1,
	},
	N_InSelec: {
		name: "N_InSelec",
		description: "(1)T_AmbC+T_BaC, (2)T_AmbC+P_Tk0C, (3)T_BaC+P_Tk0C",
		unit: "-",
		min: 1,
		max: 3,
	},
	N_LCp: {
		name: "저압 압축기 수량",
		description: "저압 압축기 수량",
		unit: "ea",
		min: 1,
	},
	N_LqPp: {
		name: "펌프 수량",
		description: "펌프 수량",
		unit: "ea",
		min: 1,
	},
	N_MCp: {
		name: "압축기 수량",
		description: "압축기 수량",
		unit: "ea",
		min: 1,
	},
	N_MCp2: {
		name: "압축기 수량",
		description: "압축기 수량",
		unit: "ea",
		min: 1,
	},
	N_OutSelec: {
		name: "N_OutSelec",
		description: "(1)T_TkMax, (2)t_Elep",
		unit: "-",
		min: 1,
		max: 2,
	},
	N_Source: {
		name: "Source의 수량",
		description: "Source(Electrolysis or Pipe)의 수량",
		unit: "ea",
		min: 1,
	},
	N_TT1: {
		name: "수량",
		description: "TT 구성 용기의 수량",
		unit: "ea",
		min: 1,
	},
	N_TT2: {
		name: "수량",
		description: "TT 구성 용기의 수량",
		unit: "ea",
		min: 1,
	},
	N_TkH: {
		name: "수량",
		description: "탱크 개수",
		unit: "ea",
		min: 1,
	},
	N_TkL: {
		name: "수량",
		description: "탱크 개수",
		unit: "ea",
		min: 1,
	},
	N_TkM: {
		name: "수량",
		description: "탱크 개수",
		unit: "ea",
		min: 1,
	},
	N_Vap: {
		name: "기화기 수량",
		description: "Vaporizer 수량",
		unit: "ea",
		min: 0,
	},
	PBUOn: {
		name: "PBUOn",
		description: "",
		unit: "",
	},
	PP_Var10: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var11: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var12: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var13: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var14: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var15: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var2: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var3: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var4: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var5: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var6: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var7: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var8: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PP_Var9: {
		name: "예비",
		description: "예비",
		unit: "",
	},
	PSVOn_LqTk: {
		name: "PSV 작동 여부",
		description: '1이면 PSV 작동, "0"이면 PSV 미작동',
		unit: "-",
		min: 0,
		max: 1,
	},
	P_BufMax1: {
		name: "내부 최고 압력",
		description: "Tank 최고압력",
		unit: "MPa",
		min: 0,
	},
	P_BufMax2: {
		name: "내부 최고 압력",
		description: "Tank 최고압력",
		unit: "MPa",
		min: 0,
	},
	P_BufMin1: {
		name: "내부 최저 압력",
		description: "Tank 최저압력",
		unit: "MPa",
		min: 0,
	},
	P_BufMin2: {
		name: "내부 최저 압력",
		description: "Tank 최저압력",
		unit: "MPa",
		min: 0,
	},
	P_Buf_01: {
		name: "초기 압력",
		description: "Tank 초기압력",
		unit: "MPa",
		min: 0,
	},
	P_Buf_02: {
		name: "초기 압력",
		description: "Tank 초기압력",
		unit: "MPa",
		min: 0,
	},
	P_Buf_RC1: {
		name: "재충전 압력",
		description: "Tank Recharge Pressure",
		unit: "MPa",
		min: 0,
	},
	P_Buf_RC2: {
		name: "재충전 압력",
		description: "Tank Recharge Pressure",
		unit: "MPa",
		min: 0,
	},
	P_Class1: {
		name: "충전소 압력 등급",
		description: "충전소 압력등급(70MPa, 35MPa 등)",
		unit: "MPa",
	},
	P_Class2: {
		name: "충전소 압력 등급",
		description: "충전소 압력등급(70MPa, 35MPa 등)",
		unit: "MPa",
	},
	P_CpInMaxH: {
		name: "P_CpInMaxH",
		description: "",
		unit: "",
	},
	P_CpInMaxL: {
		name: "P_CpInMaxL",
		description: "",
		unit: "",
	},
	P_CpInMaxM: {
		name: "P_CpInMaxM",
		description: "",
		unit: "",
	},
	P_CpInMaxM2: {
		name: "P_CpInMaxM2",
		description: "",
		unit: "",
	},
	P_CpInMinH: {
		name: "P_CpInMinH",
		description: "",
		unit: "",
	},
	P_CpInMinL: {
		name: "P_CpInMinL",
		description: "",
		unit: "",
	},
	P_CpInMinM: {
		name: "P_CpInMinM",
		description: "",
		unit: "",
	},
	P_CpInMinM2: {
		name: "P_CpInMinM2",
		description: "",
		unit: "",
	},
	P_GTkIn: {
		name: "P_GTkIn",
		description: "",
		unit: "",
	},
	P_HBk_0: {
		name: "고압뱅크 초기 압력",
		description: "HBk 초기 압력",
		unit: "MPa",
	},
	P_InH: {
		name: "펌프 인입 압력 H",
		description: "펌프 인입압력 H",
		unit: "MPa",
		min: 0,
	},
	P_InHH: {
		name: "펌프 인입 압력 HH",
		description: "펌프 인입압력 HH",
		unit: "MPa",
		min: 0,
	},
	P_LTL: {
		name: "P_LTL",
		description: "",
		unit: "",
	},
	P_OpFullRateH: {
		name: "PSV 개방개시압력 대비 완전개방압력 비율",
		description: "PSV 개방개시압력역 대비 완전개방압력 비율",
		unit: "-",
	},
	P_OpFullRateL: {
		name: "PSV 개방개시압력 대비 완전개방압력 비율",
		description: "PSV 개방개시압력역 대비 완전개방압력 비율",
		unit: "-",
	},
	P_OpFullRateM: {
		name: "PSV 개방개시압력 대비 완전개방압력 비율",
		description: "PSV 개방개시압력역 대비 완전개방압력 비율",
		unit: "-",
	},
	P_Out_LqPp: {
		name: "펌프 인출 압력",
		description: "펌프 인출 압력(Low Pressure Pump)",
		unit: "MPa",
		min: 0,
	},
	P_PSVSet_LqTk: {
		name: "분출량 결정 압력",
		description: "분출량결정압력",
		unit: "MPa",
		min: 0,
	},
	P_Source: {
		name: "Source의 압력",
		description: "Source(Electrolysis or Pipe)의 압력",
		unit: "MPa",
		min: 0,
	},
	P_TTMax1: {
		name: "내부 최고 압력",
		description: "TT 내부 최고 압력",
		unit: "MPa",
		min: 0,
	},
	P_TTMax2: {
		name: "내부 최고 압력",
		description: "TT 내부 최고 압력",
		unit: "MPa",
		min: 0,
	},
	P_TTMin1: {
		name: "내부 최저 압력",
		description: "TT 내부 최저 압력 (이 압력에서 TT 교체 (넥쏘8.5, 버스10))",
		unit: "MPa",
		min: 0,
	},
	P_TTMin2: {
		name: "내부 최저 압력",
		description: "TT 내부 최저 압력",
		unit: "MPa",
		min: 0,
	},
	P_Tk0C_Max: {
		name: "자동차 용기 최대 초기 온도",
		description: "P_Tk0C 값의 최대값",
		unit: "MPa",
		min: 0.5,
		max: 70,
	},
	P_Tk0C_Min: {
		name: "자동차 용기 최소 초기 온도",
		description: "P_Tk0C 값의 최소값",
		unit: "MPa",
		min: 0.5,
		max: 70,
	},
	P_TkMaxH: {
		name: "내부 최고 압력",
		description: "Tank 내부 최고 압력",
		unit: "MPa",
		min: 0,
	},
	P_TkMaxL: {
		name: "내부 최고 압력",
		description: "Tank 내부 최고 압력",
		unit: "MPa",
		min: 0,
	},
	P_TkMaxM: {
		name: "내부 최고 압력",
		description: "Tank 내부 최고 압력",
		unit: "MPa",
		min: 0,
	},
	P_TkMinH: {
		name: "내부 최저 압력",
		description: "Tank 내부 최저 압력",
		unit: "MPa",
		min: 0,
	},
	P_TkMinL: {
		name: "내부 최저 압력",
		description: "Tank 내부 최저 압력",
		unit: "MPa",
		min: 0,
	},
	P_TkMinM: {
		name: "내부 최저 압력",
		description: "Tank 내부 최저 압력",
		unit: "MPa",
		min: 0,
	},
	P_Tk_01: {
		name: "탱크 초기 압력",
		description: "Tank 초기 압력",
		unit: "MPa",
		min: 0,
	},
	P_Tk_02: {
		name: "탱크 초기 압력",
		description: "Tank 초기 압력",
		unit: "MPa",
		min: 0,
	},
	P_refH: {
		name: "압축기 Refrence 압력",
		description: "압축기 Refrence 압력",
		unit: "MPa",
		min: 0,
	},
	P_refL: {
		name: "압축기 Refrence 압력",
		description: "저압 압축기 Refrence 압력",
		unit: "MPa",
		min: 0,
	},
	P_refM: {
		name: "압축기 Refrence 압력",
		description: "압축기 Refrence 압력",
		unit: "MPa",
		min: 0,
	},
	P_refM2: {
		name: "압축기 Refrence 압력",
		description: "압축기 Refrence 압력",
		unit: "MPa",
		min: 0,
	},
	PpOn: {
		name: "펌프 작동 여부",
		description: '1이면 펌프 작동, "0"이면 펌프 미작동',
		unit: "-",
		min: 0,
		max: 1,
	},
	Q_Fire: {
		name: "Q_Fire",
		description: "",
		unit: "",
	},
	Q_hf_In: {
		name: "Heat flux 입력값",
		description:
			'내조 외면으로 들어가는 heat flux 입력값. 액상부의 경우 이것이 100%(Q_hf * 1) 액체가스로 전달되고, 기상부의 경우 R_QInG 비율 만큼(Q_hf * R_QInG)이 기체가스로 전달된다고 가정함. 이 값에 "0"을 입력하면 NER 기반으로 자동 계산함',
		unit: "kJ/m2-s",
		min: 0,
	},
	R_Depreciation: {
		name: "연간상각율",
		description: "연간상각율",
		unit: "%",
		min: 0,
	},
	R_Discount: {
		name: "사회적 할인율",
		description: "사회적 할인율",
		unit: "%",
		min: 0,
	},
	R_ElecBillIncrease: {
		name: "전기요금인상율",
		description: "전기요금인상율",
		unit: "%",
		min: 0,
	},
	R_GrowHDV: {
		name: "연단위 대형 차량 증가율",
		description: "연단위 Heavy Duty Vehicle 증가율",
		unit: ".",
		min: 0,
	},
	R_GrowLDV: {
		name: "연단위 소형 차량 증가율",
		description: "연단위 Light Duty Vehicle 증가율",
		unit: ".",
		min: 0,
	},
	R_H2Loss: {
		name: "충전소에서 수소 구매량 대비 손실율",
		description: "HRS에서 H2 구매량 대비  손실율",
		unit: "%",
		min: 0,
	},
	R_Inflation: {
		name: "물가인상율",
		description: "물가인상율",
		unit: "%",
		min: 0,
	},
	R_OverhGnA: {
		name: "간접비 및 일반관리비: 직접 인건비 대비 비율",
		description: "간접비 및 일반관리비: 직접 인건비 대비 비율",
		unit: "Won",
		min: 0,
	},
	R_QInG: {
		name: "열 전달율",
		description:
			"액상부와 내조 사이 열전달율이 1이라고 할 때, 기상부와 내조 사이 열전달율. 0과 1사이의 값을 가지게 됨",
		unit: "-",
		min: 0,
		max: 1,
	},
	R_SalvageVal: {
		name: "잔존가치 비율",
		description: "잔존가치 비율",
		unit: "%",
		min: 0,
	},
	R_WageIncrease: {
		name: "임금인상율",
		description: "임금인상율",
		unit: "%",
		min: 0,
	},
	S500H: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	S500M2: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	SOC_G1: {
		name: "SOC 목표",
		description: "Goal of SOC",
		unit: "%",
		min: 0,
		max: 100,
	},
	SOC_G2: {
		name: "SOC 목표",
		description: "Goal of SOC",
		unit: "%",
		min: 0,
		max: 100,
	},
	SP_LqTk_0: {
		name: "초기 압력",
		description: "LqTk 초기압력(포화압력, Saturation Pressure)",
		unit: "MPaa",
		min: 0,
	},
	SimTime: {
		name: "시뮬레이션 시간",
		description: "시뮬레이션 시간",
		unit: "s",
		min: 0,
		max: 432000,
	},
	Sp_CpH: {
		name: "압축기 분당 Speed",
		description: "압축기 분당 Speed",
		unit: "RPM",
		min: 0,
	},
	Sp_CpL: {
		name: "압축기 분당 Speed",
		description: "압축기 분당 Speed",
		unit: "RPM",
		min: 0,
	},
	Sp_CpM: {
		name: "압축기 분당 Speed",
		description: "압축기 분당 Speed",
		unit: "RPM",
		min: 0,
	},
	Sp_CpM2: {
		name: "압축기 분당 Speed",
		description: "압축기 분당 Speed",
		unit: "RPM",
		min: 0,
	},
	Sp_Ref_LqPp: {
		name: "펌프 초당 회전수",
		description: "펌프의 초당 회전(왕복)수",
		unit: "RPS",
		min: 0,
	},
	SsssH: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	SsssL: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	SsssM: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	SsssM2: {
		name: "예비",
		description: "예비",
		unit: "-",
		min: 0,
		max: 1,
	},
	TTChangeDo: {
		name: "TT Change 실행",
		description: "TT Reset 기능 사용 (1)사용, (0)미사용",
		unit: "-",
		min: 0,
		max: 1,
	},
	TV1: {
		name: "자동차 용기 전체 부피",
		description: "자동차 용기 전체의 Volume",
		unit: "L",
	},
	TV2: {
		name: "자동차 용기 전체 부피",
		description: "자동차 용기 전체의 Volume",
		unit: "L",
	},
	TVL1: {
		name: "자동차 용기 중 가장 큰 것의 부피",
		description: "자동차 용기 중 가장 큰 것의 Volume",
		unit: "L",
	},
	TVL2: {
		name: "자동차 용기 중 가장 큰 것의 부피",
		description: "자동차 용기 중 가장 큰 것의 Volume",
		unit: "L",
	},
	T_AmbC: {
		name: "대기온도",
		description: "대기온도",
		unit: "℃",
	},
	T_AmbC_Max: {
		name: "최대 대기 온도",
		description: "T_AmbC 값의 최대값",
		unit: "℃",
		min: -40,
		max: 50,
	},
	T_AmbC_Min: {
		name: "최소 대기 온도",
		description: "T_AmbC 값의 최소값",
		unit: "℃",
		min: -40,
		max: 50,
	},
	T_BaC1: {
		name: "공급 가스 온도",
		description: "공급 가스 온도",
		unit: "℃",
		min: -273.15,
		max: 50,
	},
	T_BaC2: {
		name: "공급 가스 온도",
		description: "공급 가스 온도",
		unit: "℃",
		min: -273.15,
		max: 50,
	},
	T_BaC_Max: {
		name: "Break Away 인입 최대 온도",
		description: "T_BaC 값의 최대값",
		unit: "℃",
		min: -40,
		max: -17.5,
	},
	T_BaC_Min: {
		name: "Break Away 인입 최소 온도",
		description: "T_BaC 값의 최소값",
		unit: "℃",
		min: -40,
		max: -17.5,
	},
	T_CoolSetCH: {
		name: "압축기 쿨링 목표 온도",
		description: "쿨링 목표온도",
		unit: "℃",
		min: -273.15,
	},
	T_CoolSetCL: {
		name: "압축기 쿨링 목표 온도",
		description: "쿨링 목표온도",
		unit: "℃",
		min: -273.15,
	},
	T_CoolSetCM: {
		name: "압축기 쿨링 목표 온도",
		description: "쿨링 목표온도",
		unit: "℃",
		min: -273.15,
	},
	T_CoolSetCM2: {
		name: "압축기 쿨링 목표 온도",
		description: "쿨링 목표온도",
		unit: "℃",
		min: -273.15,
	},
	T_GTkIn: {
		name: "T_GTkIn",
		description: "",
		unit: "",
	},
	T_GTkOvH: {
		name: "기상부 오버히트 온도",
		description: "액상부 비점 대비 기상부 오버히트 온도",
		unit: "K",
		min: 0,
	},
	T_InH: {
		name: "펌프 인입 온도 H",
		description: "펌프 인입온도 H",
		unit: "K",
		min: 0,
	},
	T_InHH: {
		name: "펌프 인입 온도 HH",
		description: "펌프 인입온도 HH",
		unit: "K",
		min: 0,
	},
	T_LTL: {
		name: "T_LTL",
		description: "",
		unit: "",
	},
	T_OutHeatSet: {
		name: "히터 출구 온도",
		description: "Heater 출구 온도",
		unit: "K",
		min: 0,
	},
	T_OutVapSet: {
		name: "기화기 출구 온도",
		description: "Vaporizer 출구 온도",
		unit: "K",
		min: 0,
	},
	T_SourceC: {
		name: "Source의 온도",
		description: "Source(Electrolysis or Pipe)의 온도",
		unit: "℃",
		min: -273.15,
	},
	T_TT_0C1: {
		name: "내부 온도",
		description: 'T_TT_0C에 "-1"을 입력하면 T_Amb가 T_TT_0에 적용됨',
		unit: "℃",
	},
	T_TT_0C2: {
		name: "내부 온도",
		description: 'T_Tk_0C에 "-1"을 입력하면 T_Amb가 T_Tk_0에 적용됨',
		unit: "℃",
		min: -273.15,
	},
	T_Tk_0C1: {
		name: "탱크 초기 온도",
		description: 'Tank 초기 온도. "999"를 입력하면 T_Amb를 T_Tk_0로 봄.',
		unit: "℃",
		min: -273.15,
	},
	T_Tk_0C2: {
		name: "탱크 초기 온도",
		description: 'Tank 초기 온도. "999"를 입력하면 T_Amb를 T_Tk_0로 봄.',
		unit: "℃",
		min: -273.15,
	},
	T_Tk_0CH: {
		name: "내부 온도",
		description: 'Tank 내부 초기온도. "999" 입력시 T_Amb로 대체됨',
		unit: "℃",
		min: -273.15,
	},
	T_Tk_0CL: {
		name: "내부 온도",
		description:
			'Tank 내부 초기 온도. T_Tk_0C에 "-1"을 입력하면 T_Amb가 T_Tk_0에 적용됨.',
		unit: "℃",
		min: -273.15,
	},
	T_Tk_0CM: {
		name: "내부 온도",
		description:
			'Tank 내부 초기 온도. T_Tk_0C에 "-1"을 입력하면 T_Amb가 T_Tk_0에 적용됨.',
		unit: "℃",
		min: -273.15,
	},
	T_refCH: {
		name: "압축기 Refrence 온도",
		description: "압축기 Refrence 온도",
		unit: "℃",
		min: -273.15,
	},
	T_refCL: {
		name: "압축기 Refrence 온도",
		description: "저압 압축기 Refrence 온도",
		unit: "℃",
		min: -273.15,
	},
	T_refCM: {
		name: "압축기 Refrence 온도",
		description: "압축기 Refrence 온도",
		unit: "℃",
		min: -273.15,
	},
	T_refCM2: {
		name: "압축기 Refrence 온도",
		description: "압축기 Refrence 온도",
		unit: "℃",
		min: -273.15,
	},
	Target_NFu: {
		name: "몇대 충전후 TT 또는 Bk Reset",
		description: "모빌리티 Target_NFu대 충전 후 TT Reset 적용",
		unit: "ea",
		min: 1,
	},
	Term_Refill: {
		name: "Bk Reset을 위한 Refill 시간",
		description: "Bank Refill 시간",
		unit: "s",
		min: 0,
	},
	Thick_Buf1: {
		name: "용기 동판 두께",
		description: "단위 Tank 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_Buf2: {
		name: "용기 동판 두께",
		description: "단위 Tank 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_TT1: {
		name: "용기 동판 두께",
		description: "TT 용기 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_TT2: {
		name: "용기 동판 두께",
		description: "TT 용기 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_TkH: {
		name: "용기 동판 두께",
		description: "단위 Tank 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_TkL: {
		name: "용기 동판 두께",
		description: "단위 Tank 동판 두께",
		unit: "m",
		min: 0,
	},
	Thick_TkM: {
		name: "용기 동판 두께",
		description: "단위 Tank 동판 두께",
		unit: "m",
		min: 0,
	},
	TwH: {
		name: "탱크 표면 온도",
		description: "Tank 표면온도",
		unit: "K",
	},
	TwL: {
		name: "탱크 표면 온도",
		description: "Tank 표면온도",
		unit: "K",
	},
	TwM: {
		name: "탱크 표면 온도",
		description: "Tank 표면온도",
		unit: "K",
	},
	Use_ChR: {
		name: "사용량 요금",
		description: "사용량요금",
		unit: "Won/kW",
		min: 0,
	},
	V_BufInd1: {
		name: "부피",
		description: "개별 Tank의 Volume",
		unit: "m3",
		min: 0,
	},
	V_BufInd2: {
		name: "부피",
		description: "개별 Tank의 Volume",
		unit: "m3",
		min: 0,
	},
	V_LqTk: {
		name: "부피",
		description: "탱크의 Volume",
		unit: "m3",
		min: 0,
	},
	V_TTInd1: {
		name: "부피",
		description: "TT 구성 용기 1개의 체적",
		unit: "m3",
		min: 0,
	},
	V_TTInd2: {
		name: "부피",
		description: "TT 구성 용기 1개의 체적",
		unit: "m3",
		min: 0,
	},
	V_TkIndH: {
		name: "부피",
		description: "개별 Tank의 부피",
		unit: "m3",
		min: 0,
	},
	V_TkIndL: {
		name: "부피",
		description: "개별 Tank의 부피",
		unit: "m3",
		min: 0,
	},
	V_TkIndM: {
		name: "부피",
		description: "개별 Tank의 부피",
		unit: "m3",
		min: 0,
	},
	V_TkMode1: {
		name: "자동차 용기 Volume",
		description: 'Tank Volume의 종류. "11"은 넥소, 12는 일렉시티임.',
		unit: "-",
		min: 0,
	},
	V_TkMode2: {
		name: "자동차 용기 Volume",
		description: 'Tank Volume의 종류. "11"은 넥소, 12는 일렉시티임.',
		unit: "-",
		min: 0,
	},
	V_ref_LqPp: {
		name: "실제 이송 체적",
		description: "Pump 1회전당 실재 이송 체적",
		unit: "m3/h",
		min: 0,
	},
	VapElecOn: {
		name: "기화기 에너지원",
		description: "Vaporizer 에너지원 (0)대기식, (1)전기식",
		unit: "-",
		min: 0,
		max: 1,
	},
	WagePerHr: {
		name: "시급",
		description: "시급",
		unit: "Won/hr",
		min: 0,
	},
	WorkHrPerDay: {
		name: "1일 근무 시간",
		description: "1일 근무 시간",
		unit: "hr",
		min: 0,
	},
	Yr_Base: {
		name: "기준연도",
		description: "기준연도",
		unit: "Yr",
		min: 0,
	},
	Yr_DoStart: {
		name: "운영개시연도",
		description: "운영개시연도",
		unit: "Yr",
		min: 0,
	},
	Yr_EE: {
		name: "경제성평가 기간",
		description: "경제성평가 기간",
		unit: "Yr",
		min: 0,
	},
	Yr_Life: {
		name: "내용수명",
		description: "내용수명",
		unit: "yr",
		min: 0,
	},
	dP_BkCh1: {
		name: "Bank Charge 실행 차압",
		description:
			"Bank change 실행 차압(FCV최소 입구압력보다 dP_BkCh 만큼 더 높은 압력에서 Bank change 실행)",
		unit: "MPa",
		min: 0,
	},
	dP_BkCh2: {
		name: "Bank Charge 실행 차압",
		description:
			"Bank change 실행 차압(FCV최소 입구압력보다 dP_BkCh 만큼 더 높은 압력에서 Bank change 실행)",
		unit: "MPa",
		min: 0,
	},
	d_BufInlet1: {
		name: "용기 입구 직경",
		description: "단위 Tank 입구 직경",
		unit: "m",
		min: 0,
	},
	d_BufInlet2: {
		name: "용기 입구 직경",
		description: "단위 Tank 입구 직경",
		unit: "m",
		min: 0,
	},
	d_BufOutlet1: {
		name: "용기 출구 직경",
		description: "단위 Tank 출구 직경",
		unit: "m",
		min: 0,
	},
	d_BufOutlet2: {
		name: "용기 출구 직경",
		description: "단위 Tank 출구 직경",
		unit: "m",
		min: 0,
	},
	d_In1301: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_In1302: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_In1401: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_In1402: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_In1501: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_In1502: {
		name: "충전라인 입구 직경",
		description: "충전라인 입구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1301: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1302: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1401: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1402: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1501: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_Out1502: {
		name: "충전라인 출구 직경",
		description: "충전라인 출구 직경",
		unit: "m",
		min: 0,
	},
	d_TTInlet1: {
		name: "용기 입구 직경",
		description: "TT 용기 입구 직경",
		unit: "m",
		min: 0,
	},
	d_TTInlet2: {
		name: "용기 입구 직경",
		description: "TT 용기 입구 직경",
		unit: "m",
		min: 0,
	},
	d_TTOutlet1: {
		name: "용기 출구 직경",
		description: "TT 용기 출구 직경",
		unit: "m",
		min: 0,
	},
	d_TTOutlet2: {
		name: "용기 출구 직경",
		description: "TT 용기 출구 직경",
		unit: "m",
		min: 0,
	},
	d_TkInletH: {
		name: "용기 입구 직경",
		description: "단위 Tank 입구 직경",
		unit: "m",
		min: 0,
	},
	d_TkInletL: {
		name: "용기 입구 직경",
		description: "단위 Tank 입구 직경",
		unit: "m",
		min: 0,
	},
	d_TkInletM: {
		name: "용기 입구 직경",
		description: "단위 Tank 입구 직경",
		unit: "m",
		min: 0,
	},
	d_TkOutletH: {
		name: "용기 출구 직경",
		description: "단위 Tank 출구 직경",
		unit: "m",
		min: 0,
	},
	d_TkOutletL: {
		name: "용기 출구 직경",
		description: "단위 Tank 출구 직경",
		unit: "m",
		min: 0,
	},
	d_TkOutletM: {
		name: "용기 출구 직경",
		description: "단위 Tank 출구 직경",
		unit: "m",
		min: 0,
	},
	dt_BOG: {
		name: "BOG Time Step",
		description: "BOG Simulation 전용 SFC에서 적용하는 Time Step",
		unit: "s",
		min: 0.5,
	},
	eta_v_LPPp: {
		name: "펌프 체적 효율성",
		description: "펌프 Voumetric Efficiency",
		unit: "-",
		min: 0,
	},
	k_BufComp1: {
		name: "동판 복합재료 열전도도",
		description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_BufComp2: {
		name: "동판 복합재료 열전도도",
		description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_BufLin1: {
		name: "동판 라이너 여전도도",
		description: "단위 Tank 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_BufLin2: {
		name: "동판 라이너 열전도도",
		description: "단위 Tank 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_CompH: {
		name: "동판 복합재료 열전도도",
		description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_CompL: {
		name: "동판 복합재료 열전도도",
		description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_CompM: {
		name: "동판 복합재료 열전도도",
		description: "단위 Tank 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_LinH: {
		name: "동판 라이너 열전도도",
		description: "단위 Tank 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_LinL: {
		name: "동판 라이너 열전도도",
		description: "단위 Tank 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_LinM: {
		name: "동판 라이너 열전도도",
		description: "단위 Tank 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_TTComp1: {
		name: "동판 복합재료 열전도도",
		description: "TT 용기 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_TTComp2: {
		name: "동판 복합재료 열전도도",
		description: "TT 용기 동판 복합재료 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_TTLin1: {
		name: "동판 라이너 열전도도",
		description: "TT 용기 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	k_TTLin2: {
		name: "동판 라이너 열전도도",
		description: "TT 용기 동판 라이너 열전도도(thermal conductivity)",
		unit: "kW/mK",
		min: 0,
	},
	m_Cp_refH: {
		name: "압축기 Refrence 용량",
		description: "압축기 Refrence 용량",
		unit: "kg/h",
		min: 0,
	},
	m_Cp_refL: {
		name: "압축기 Refrence 용량",
		description: "저압 압축기 Refrence 용량",
		unit: "kg/h",
		min: 0,
	},
	m_Cp_refM: {
		name: "압축기 Refrence 용량",
		description: "압축기 Refrence 용량",
		unit: "kg/h",
		min: 0,
	},
	m_Cp_refM2: {
		name: "압축기 Refrence 용량",
		description: "압축기 Refrence 용량",
		unit: "kg/h",
		min: 0,
	},
	m_GTkIn: {
		name: "m_GTkIn",
		description: "",
		unit: "",
	},
	m_HFPLim1: {
		name: "충전 유량 상한",
		description: "충전 유량 상한",
		unit: "g/s",
		min: 60,
		max: 300,
	},
	m_HFPLim2: {
		name: "충전 유량 상한",
		description: "충전 유량 상한",
		unit: "g/s",
		min: 60,
		max: 300,
	},
	m_LTL: {
		name: "m_LTL",
		description: "",
		unit: "",
	},
	m_LTkOut: {
		name: "m_LTkOut",
		description: "",
		unit: "",
	},
	m_PSVCa_LqTk: {
		name: "PSV 분출 용량",
		description: "PSV 분출용량",
		unit: "kg/h",
		min: 0,
	},
	m_Source: {
		name: "Source의 유량",
		description: "Source(Electrolysis or Pipe)의 유량",
		unit: "kg/h",
		min: 0,
	},
	m_VapCapa: {
		name: "기화기 증방 용량",
		description: "Vaporizer 증발용량",
		unit: "kg/h",
		min: 0,
	},
	rho_BufComp1: {
		name: "동판 복합재료 밀도",
		description: "단위 Tank 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_BufComp2: {
		name: "동판 복합재료 밀도",
		description: "단위 Tank 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_BufLin1: {
		name: "동판 라이너 밀도",
		description: "단위 Tank 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_BufLin2: {
		name: "동판 라이너 밀도",
		description: "단위 Tank 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_CompH: {
		name: "동판 복합재료 밀도",
		description: "단위 Tank 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_CompL: {
		name: "동판 복합재료 밀도",
		description: "단위 Tank 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_CompM: {
		name: "동판 복합재료 밀도",
		description: "단위 Tank 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_LinH: {
		name: "동판 라이너 밀도",
		description: "단위 Tank 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_LinL: {
		name: "동판 라이너 밀도",
		description: "단위 Tank 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_LinM: {
		name: "동판 라이너 밀도",
		description: "단위 Tank 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_TTComp1: {
		name: "동판 복합재료 밀도",
		description: "TT 용기 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_TTComp2: {
		name: "동판 복합재료 밀도",
		description: "TT 용기 동판 복합재료 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_TTLin1: {
		name: "동판 라이너 밀도",
		description: "TT 용기 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	rho_TTLin2: {
		name: "동판 라이너 밀도",
		description: "TT 용기 동판 라이너 밀도",
		unit: "kg/m3",
		min: 0,
	},
	t_BrkHDV: {
		name: "대형 차량 충전 준비 시간",
		description: "HDV 충전 준비 시간",
		unit: "sec",
		min: 0,
	},
	t_BrkLDV: {
		name: "소형 차량 충전 준비 시간",
		description: "LDV 충전 준비 시간",
		unit: "sec",
		min: 0,
	},
	t_BrkMax1: {
		name: "충전과 충전 사이의 준비 시간",
		description: "충전과 충전 사이의 준비 시간",
		unit: "s",
		min: 0,
	},
	t_BrkMax2: {
		name: "충전과 충전 사이의 준비 시간",
		description: "충전과 충전 사이의 준비 시간",
		unit: "s",
		min: 0,
	},
	t_FuHDV: {
		name: "대형 차량 충전 소요 시간",
		description: "HDV 충전 소요 시간",
		unit: "sec",
		min: 0,
	},
	t_FuLDV: {
		name: "소형 차량 충전 소요 시간",
		description: "LDV 충전 소요 시간",
		unit: "sec",
		min: 0,
	},
	t_PreRun: {
		name: "버퍼탱크 충전 시간",
		description: "Buffer Tk 충전시간. 이 시간 동안 모빌리티 충전은 대기",
		unit: "min",
		min: 0,
	},
	t_PreSet1: {
		name: "시뮬레이션 전 디스펜서 1 세팅 시간",
		description: "시뮬레이션 시작 전, Dispenser1의 Setting 시간",
		unit: "s",
		min: 0,
	},
	t_PreSet2: {
		name: "시뮬레이션 전 디스펜서 2 세팅 시간",
		description: "시뮬레이션 시작 전, Dispenser2의 Setting 시간",
		unit: "s",
		min: 0,
	},
	tol: {
		name: "tol",
		description: "tol",
		unit: "-",
		min: 0,
	},
	x10_Cp: {
		name: "압축기 처리용량 사례10",
		description: "압축기 처리용량 사례10",
		unit: "kg/h",
		min: 0,
	},
	x10_Disp: {
		name: "충전기 대수 사례10",
		description: "Dispenser 대수 사례10",
		unit: "ea",
		min: 0,
	},
	x10_Elec: {
		name: "bhp값 사례10",
		description: "bhp값 사례10",
		unit: "bhp",
		min: 0,
	},
	x10_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례10",
		description: "압력 48MPa 이상 Bank 저장용량 사례10",
		unit: "kg",
		min: 0,
	},
	x10_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례10",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례10",
		unit: "kg",
		min: 0,
	},
	x10_LqPp: {
		name: "펌프 처리능력 사례10",
		description: "Lq 펌프 처리능력 사례10",
		unit: "kg/h",
		min: 0,
	},
	x10_LqTk: {
		name: "탱크 저장능력 사례10",
		description: "Lq 저장탱크 저장능력 사례10",
		unit: "kg",
		min: 0,
	},
	x10_Vap: {
		name: "기화기 처리능력 사례10",
		description: "Lq 기화기 처리능력 사례10",
		unit: "kg/h",
		min: 0,
	},
	x10_YrPrice: {
		name: "연도 사례10",
		description: "연도 사례10",
		unit: "Yr",
		min: 0,
	},
	x10_YrPurch: {
		name: "연도 사례10",
		description: "연도 사례10",
		unit: "Yr",
		min: 0,
	},
	x11_Cp: {
		name: "압축기 처리용량 사례11",
		description: "압축기 처리용량 사례11",
		unit: "kg/h",
		min: 0,
	},
	x11_Disp: {
		name: "충전기 대수 사례11",
		description: "Dispenser 대수 사례11",
		unit: "ea",
		min: 0,
	},
	x11_Elec: {
		name: "bhp값 사례11",
		description: "bhp값 사례11",
		unit: "bhp",
		min: 0,
	},
	x11_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례11",
		description: "압력 48MPa 이상 Bank 저장용량 사례11",
		unit: "kg",
		min: 0,
	},
	x11_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례11",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례11",
		unit: "kg",
		min: 0,
	},
	x11_LqPp: {
		name: "펌프 처리능력 사례11",
		description: "Lq 펌프 처리능력 사례11",
		unit: "kg/h",
		min: 0,
	},
	x11_LqTk: {
		name: "탱크 저장능력 사례11",
		description: "Lq 저장탱크 저장능력 사례11",
		unit: "kg",
		min: 0,
	},
	x11_Vap: {
		name: "기화기 처리능력 사례11",
		description: "Lq 기화기 처리능력 사례11",
		unit: "kg/h",
		min: 0,
	},
	x11_YrPrice: {
		name: "연도 사례11",
		description: "연도 사례11",
		unit: "Yr",
		min: 0,
	},
	x11_YrPurch: {
		name: "연도 사례11",
		description: "연도 사례11",
		unit: "Yr",
		min: 0,
	},
	x12_Cp: {
		name: "압축기 처리용량 사례12",
		description: "압축기 처리용량 사례12",
		unit: "kg/h",
		min: 0,
	},
	x12_Disp: {
		name: "충전기 대수 사례12",
		description: "Dispenser 대수 사례12",
		unit: "ea",
		min: 0,
	},
	x12_Elec: {
		name: "bhp값 사례12",
		description: "bhp값 사례12",
		unit: "bhp",
		min: 0,
	},
	x12_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례12",
		description: "압력 48MPa 이상 Bank 저장용량 사례12",
		unit: "kg",
		min: 0,
	},
	x12_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례12",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례12",
		unit: "kg",
		min: 0,
	},
	x12_LqPp: {
		name: "펌프 처리능력 사례12",
		description: "Lq 펌프 처리능력 사례12",
		unit: "kg/h",
		min: 0,
	},
	x12_LqTk: {
		name: "탱크 저장능력 사례12",
		description: "Lq 저장탱크 저장능력 사례12",
		unit: "kg",
		min: 0,
	},
	x12_Vap: {
		name: "기화기 처리능력 사례12",
		description: "Lq 기화기 처리능력 사례12",
		unit: "kg/h",
		min: 0,
	},
	x12_YrPrice: {
		name: "연도 사례12",
		description: "연도 사례12",
		unit: "Yr",
		min: 0,
	},
	x12_YrPurch: {
		name: "연도 사례12",
		description: "연도 사례12",
		unit: "Yr",
		min: 0,
	},
	x13_Cp: {
		name: "압축기 처리용량 사례13",
		description: "압축기 처리용량 사례13",
		unit: "kg/h",
		min: 0,
	},
	x13_Disp: {
		name: "충전기 대수 사례13",
		description: "Dispenser 대수 사례13",
		unit: "ea",
		min: 0,
	},
	x13_Elec: {
		name: "bhp값 사례13",
		description: "bhp값 사례13",
		unit: "bhp",
		min: 0,
	},
	x13_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례13",
		description: "압력 48MPa 이상 Bank 저장용량 사례13",
		unit: "kg",
		min: 0,
	},
	x13_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례13",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례13",
		unit: "kg",
		min: 0,
	},
	x13_LqPp: {
		name: "펌프 처리능력 사례13",
		description: "Lq 펌프 처리능력 사례13",
		unit: "kg/h",
		min: 0,
	},
	x13_LqTk: {
		name: "탱크 저장능력 사례13",
		description: "Lq 저장탱크 저장능력 사례13",
		unit: "kg",
		min: 0,
	},
	x13_Vap: {
		name: "기화기 처리능력 사례13",
		description: "Lq 기화기 처리능력 사례13",
		unit: "kg/h",
		min: 0,
	},
	x13_YrPrice: {
		name: "연도 사례13",
		description: "연도 사례13",
		unit: "Yr",
		min: 0,
	},
	x13_YrPurch: {
		name: "연도 사례13",
		description: "연도 사례13",
		unit: "Yr",
		min: 0,
	},
	x14_Cp: {
		name: "압축기 처리용량 사례14",
		description: "압축기 처리용량 사례14",
		unit: "kg/h",
		min: 0,
	},
	x14_Disp: {
		name: "충전기 대수 사례14",
		description: "Dispenser 대수 사례14",
		unit: "ea",
		min: 0,
	},
	x14_Elec: {
		name: "bhp값 사례14",
		description: "bhp값 사례14",
		unit: "bhp",
		min: 0,
	},
	x14_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례14",
		description: "압력 48MPa 이상 Bank 저장용량 사례14",
		unit: "kg",
		min: 0,
	},
	x14_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례14",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례14",
		unit: "kg",
		min: 0,
	},
	x14_LqPp: {
		name: "펌프 처리능력 사례14",
		description: "Lq 펌프 처리능력 사례14",
		unit: "kg/h",
		min: 0,
	},
	x14_LqTk: {
		name: "탱크 저장능력 사례14",
		description: "Lq 저장탱크 저장능력 사례14",
		unit: "kg",
		min: 0,
	},
	x14_Vap: {
		name: "기화기 처리능력 사례14",
		description: "Lq 기화기 처리능력 사례14",
		unit: "kg/h",
		min: 0,
	},
	x14_YrPrice: {
		name: "연도 사례14",
		description: "연도 사례14",
		unit: "Yr",
		min: 0,
	},
	x14_YrPurch: {
		name: "연도 사례14",
		description: "연도 사례14",
		unit: "Yr",
		min: 0,
	},
	x15_Cp: {
		name: "압축기 처리용량 사례15",
		description: "압축기 처리용량 사례15",
		unit: "kg/h",
		min: 0,
	},
	x15_Disp: {
		name: "충전기 대수 사례15",
		description: "Dispenser 대수 사례15",
		unit: "ea",
		min: 0,
	},
	x15_Elec: {
		name: "bhp값 사례15",
		description: "bhp값 사례15",
		unit: "bhp",
		min: 0,
	},
	x15_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례15",
		description: "압력 48MPa 이상 Bank 저장용량 사례15",
		unit: "kg",
		min: 0,
	},
	x15_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례15",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례15",
		unit: "kg",
		min: 0,
	},
	x15_LqPp: {
		name: "펌프 처리능력 사례15",
		description: "Lq 펌프 처리능력 사례15",
		unit: "kg/h",
		min: 0,
	},
	x15_LqTk: {
		name: "탱크 저장능력 사례15",
		description: "Lq 저장탱크 저장능력 사례15",
		unit: "kg",
		min: 0,
	},
	x15_Vap: {
		name: "기화기 처리능력 사례15",
		description: "Lq 기화기 처리능력 사례15",
		unit: "kg/h",
		min: 0,
	},
	x15_YrPrice: {
		name: "연도 사례15",
		description: "연도 사례15",
		unit: "Yr",
		min: 0,
	},
	x15_YrPurch: {
		name: "연도 사례15",
		description: "연도 사례15",
		unit: "Yr",
		min: 0,
	},
	x1_Cp: {
		name: "압축기 처리용량 사례1",
		description: "압축기 처리용량 사례1",
		unit: "kg/h",
		min: 0,
	},
	x1_Disp: {
		name: "충전기 대수 사례1",
		description: "Dispenser 대수 사례1",
		unit: "ea",
		min: 0,
	},
	x1_Elec: {
		name: "bhp값 사례1",
		description: "bhp값 사례1",
		unit: "bhp",
		min: 0,
	},
	x1_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례1",
		description: "압력 48MPa 이상 Bank 저장용량 사례1",
		unit: "kg",
		min: 0,
	},
	x1_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례1",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례1",
		unit: "kg",
		min: 0,
	},
	x1_LqPp: {
		name: "펌프 처리능력 사례1",
		description: "Lq 펌프 처리능력 사례1",
		unit: "kg/h",
		min: 0,
	},
	x1_LqTk: {
		name: "탱크 저장능력 사례1",
		description: "Lq 저장탱크 저장능력 사례1",
		unit: "kg",
		min: 0,
	},
	x1_Vap: {
		name: "기화기 처리능력 사례1",
		description: "Lq 기화기 처리능력 사례1",
		unit: "kg/h",
		min: 0,
	},
	x1_YrPrice: {
		name: "연도 사례1",
		description: "연도 사례1",
		unit: "Yr",
		min: 0,
	},
	x1_YrPurch: {
		name: "연도 사례1",
		description: "연도 사례1",
		unit: "Yr",
		min: 0,
	},
	x2_Cp: {
		name: "압축기 처리용량 사례2",
		description: "압축기 처리용량 사례2",
		unit: "kg/h",
		min: 0,
	},
	x2_Disp: {
		name: "충전기 대수 사례2",
		description: "Dispenser 대수 사례2",
		unit: "ea",
		min: 0,
	},
	x2_Elec: {
		name: "bhp값 사례2",
		description: "bhp값 사례2",
		unit: "bhp",
		min: 0,
	},
	x2_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례2",
		description: "압력 48MPa 이상 Bank 저장용량 사례2",
		unit: "kg",
		min: 0,
	},
	x2_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례2",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례2",
		unit: "kg",
		min: 0,
	},
	x2_LqPp: {
		name: "펌프 처리능력 사례2",
		description: "Lq 펌프 처리능력 사례2",
		unit: "kg/h",
		min: 0,
	},
	x2_LqTk: {
		name: "탱크 저장능력 사례2",
		description: "Lq 저장탱크 저장능력 사례2",
		unit: "kg",
		min: 0,
	},
	x2_Vap: {
		name: "기화기 처리능력 사례2",
		description: "Lq 기화기 처리능력 사례2",
		unit: "kg/h",
		min: 0,
	},
	x2_YrPrice: {
		name: "연도 사례2",
		description: "연도 사례2",
		unit: "Yr",
		min: 0,
	},
	x2_YrPurch: {
		name: "연도 사례2",
		description: "연도 사례2",
		unit: "Yr",
		min: 0,
	},
	x3_Cp: {
		name: "압축기 처리용량 사례3",
		description: "압축기 처리용량 사례3",
		unit: "kg/h",
		min: 0,
	},
	x3_Disp: {
		name: "충전기 대수 사례3",
		description: "Dispenser 대수 사례3",
		unit: "ea",
		min: 0,
	},
	x3_Elec: {
		name: "bhp값 사례3",
		description: "bhp값 사례3",
		unit: "bhp",
		min: 0,
	},
	x3_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례3",
		description: "압력 48MPa 이상 Bank 저장용량 사례3",
		unit: "kg",
		min: 0,
	},
	x3_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례3",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례3",
		unit: "kg",
		min: 0,
	},
	x3_LqPp: {
		name: "펌프 처리능력 사례3",
		description: "Lq 펌프 처리능력 사례3",
		unit: "kg/h",
		min: 0,
	},
	x3_LqTk: {
		name: "탱크 저장능력 사례3",
		description: "Lq 저장탱크 저장능력 사례3",
		unit: "kg",
		min: 0,
	},
	x3_Vap: {
		name: "기화기 처리능력 사례3",
		description: "Lq 기화기 처리능력 사례3",
		unit: "kg/h",
		min: 0,
	},
	x3_YrPrice: {
		name: "연도 사례3",
		description: "연도 사례3",
		unit: "Yr",
		min: 0,
	},
	x3_YrPurch: {
		name: "연도 사례3",
		description: "연도 사례3",
		unit: "Yr",
		min: 0,
	},
	x4_Cp: {
		name: "압축기 처리용량 사례4",
		description: "압축기 처리용량 사례4",
		unit: "kg/h",
		min: 0,
	},
	x4_Disp: {
		name: "충전기 대수 사례4",
		description: "Dispenser 대수 사례4",
		unit: "ea",
		min: 0,
	},
	x4_Elec: {
		name: "bhp값 사례4",
		description: "bhp값 사례4",
		unit: "bhp",
		min: 0,
	},
	x4_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례4",
		description: "압력 48MPa 이상 Bank 저장용량 사례4",
		unit: "kg",
		min: 0,
	},
	x4_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례4",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례4",
		unit: "kg",
		min: 0,
	},
	x4_LqPp: {
		name: "펌프 처리능력 사례4",
		description: "Lq 펌프 처리능력 사례4",
		unit: "kg/h",
		min: 0,
	},
	x4_LqTk: {
		name: "탱크 저장능력 사례4",
		description: "Lq 저장탱크 저장능력 사례4",
		unit: "kg",
		min: 0,
	},
	x4_Vap: {
		name: "기화기 처리능력 사례4",
		description: "Lq 기화기 처리능력 사례4",
		unit: "kg/h",
		min: 0,
	},
	x4_YrPrice: {
		name: "연도 사례4",
		description: "연도 사례4",
		unit: "Yr",
		min: 0,
	},
	x4_YrPurch: {
		name: "연도 사례4",
		description: "연도 사례4",
		unit: "Yr",
		min: 0,
	},
	x5_Cp: {
		name: "압축기 처리용량 사례5",
		description: "압축기 처리용량 사례5",
		unit: "kg/h",
		min: 0,
	},
	x5_Disp: {
		name: "충전기 대수 사례5",
		description: "Dispenser 대수 사례5",
		unit: "ea",
		min: 0,
	},
	x5_Elec: {
		name: "bhp값 사례5",
		description: "bhp값 사례5",
		unit: "bhp",
		min: 0,
	},
	x5_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례5",
		description: "압력 48MPa 이상 Bank 저장용량 사례5",
		unit: "kg",
		min: 0,
	},
	x5_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례5",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례5",
		unit: "kg",
		min: 0,
	},
	x5_LqPp: {
		name: "펌프 처리능력 사례5",
		description: "Lq 펌프 처리능력 사례5",
		unit: "kg/h",
		min: 0,
	},
	x5_LqTk: {
		name: "탱크 저장능력 사례5",
		description: "Lq 저장탱크 저장능력 사례5",
		unit: "kg",
		min: 0,
	},
	x5_Vap: {
		name: "기화기 처리능력 사례5",
		description: "Lq 기화기 처리능력 사례5",
		unit: "kg/h",
		min: 0,
	},
	x5_YrPrice: {
		name: "연도 사례5",
		description: "연도 사례5",
		unit: "Yr",
		min: 0,
	},
	x5_YrPurch: {
		name: "연도 사례5",
		description: "연도 사례5",
		unit: "Yr",
		min: 0,
	},
	x6_Cp: {
		name: "압축기 처리용량 사례6",
		description: "압축기 처리용량 사례6",
		unit: "kg/h",
		min: 0,
	},
	x6_Disp: {
		name: "충전기 대수 사례6",
		description: "Dispenser 대수 사례6",
		unit: "ea",
		min: 0,
	},
	x6_Elec: {
		name: "bhp값 사례6",
		description: "bhp값 사례6",
		unit: "bhp",
		min: 0,
	},
	x6_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례6",
		description: "압력 48MPa 이상 Bank 저장용량 사례6",
		unit: "kg",
		min: 0,
	},
	x6_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례6",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례6",
		unit: "kg",
		min: 0,
	},
	x6_LqPp: {
		name: "펌프 처리능력 사례6",
		description: "Lq 펌프 처리능력 사례6",
		unit: "kg/h",
		min: 0,
	},
	x6_LqTk: {
		name: "탱크 저장능력 사례6",
		description: "Lq 저장탱크 저장능력 사례6",
		unit: "kg",
		min: 0,
	},
	x6_Vap: {
		name: "기화기 처리능력 사례6",
		description: "Lq 기화기 처리능력 사례6",
		unit: "kg/h",
		min: 0,
	},
	x6_YrPrice: {
		name: "연도 사례6",
		description: "연도 사례6",
		unit: "Yr",
		min: 0,
	},
	x6_YrPurch: {
		name: "연도 사례6",
		description: "연도 사례6",
		unit: "Yr",
		min: 0,
	},
	x7_Cp: {
		name: "압축기 처리용량 사례7",
		description: "압축기 처리용량 사례7",
		unit: "kg/h",
		min: 0,
	},
	x7_Disp: {
		name: "충전기 대수 사례7",
		description: "Dispenser 대수 사례7",
		unit: "ea",
		min: 0,
	},
	x7_Elec: {
		name: "bhp값 사례7",
		description: "bhp값 사례7",
		unit: "bhp",
		min: 0,
	},
	x7_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례7",
		description: "압력 48MPa 이상 Bank 저장용량 사례7",
		unit: "kg",
		min: 0,
	},
	x7_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례7",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례7",
		unit: "kg",
		min: 0,
	},
	x7_LqPp: {
		name: "펌프 처리능력 사례7",
		description: "Lq 펌프 처리능력 사례7",
		unit: "kg/h",
		min: 0,
	},
	x7_LqTk: {
		name: "탱크 저장능력 사례7",
		description: "Lq 저장탱크 저장능력 사례7",
		unit: "kg",
		min: 0,
	},
	x7_Vap: {
		name: "기화기 처리능력 사례7",
		description: "Lq 기화기 처리능력 사례7",
		unit: "kg/h",
		min: 0,
	},
	x7_YrPrice: {
		name: "연도 사례7",
		description: "연도 사례7",
		unit: "Yr",
		min: 0,
	},
	x7_YrPurch: {
		name: "연도 사례7",
		description: "연도 사례7",
		unit: "Yr",
		min: 0,
	},
	x8_Cp: {
		name: "압축기 처리용량 사례8",
		description: "압축기 처리용량 사례8",
		unit: "kg/h",
		min: 0,
	},
	x8_Disp: {
		name: "충전기 대수 사례8",
		description: "Dispenser 대수 사례8",
		unit: "ea",
		min: 0,
	},
	x8_Elec: {
		name: "bhp값 사례8",
		description: "bhp값 사례8",
		unit: "bhp",
		min: 0,
	},
	x8_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례8",
		description: "압력 48MPa 이상 Bank 저장용량 사례8",
		unit: "kg",
		min: 0,
	},
	x8_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례8",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례8",
		unit: "kg",
		min: 0,
	},
	x8_LqPp: {
		name: "펌프 처리능력 사례8",
		description: "Lq 펌프 처리능력 사례8",
		unit: "kg/h",
		min: 0,
	},
	x8_LqTk: {
		name: "탱크 저장능력 사례8",
		description: "Lq 저장탱크 저장능력 사례8",
		unit: "kg",
		min: 0,
	},
	x8_Vap: {
		name: "기화기 처리능력 사례8",
		description: "Lq 기화기 처리능력 사례8",
		unit: "kg/h",
		min: 0,
	},
	x8_YrPrice: {
		name: "연도 사례8",
		description: "연도 사례8",
		unit: "Yr",
		min: 0,
	},
	x8_YrPurch: {
		name: "연도 사례8",
		description: "연도 사례8",
		unit: "Yr",
		min: 0,
	},
	x9_Cp: {
		name: "압축기 처리용량 사례9",
		description: "압축기 처리용량 사례9",
		unit: "kg/h",
		min: 0,
	},
	x9_Disp: {
		name: "충전기 대수 사례9",
		description: "Dispenser 대수 사례9",
		unit: "ea",
		min: 0,
	},
	x9_Elec: {
		name: "bhp값 사례9",
		description: "bhp값 사례9",
		unit: "bhp",
		min: 0,
	},
	x9_HBk: {
		name: "48MPa 이상 뱅크 저장용량 사례9",
		description: "압력 48MPa 이상 Bank 저장용량 사례9",
		unit: "kg",
		min: 0,
	},
	x9_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 저장용량 사례9",
		description: "압력 48MPa 미만 Bank 및 Buffer저장용량 사례9",
		unit: "kg",
		min: 0,
	},
	x9_LqPp: {
		name: "펌프 처리능력 사례9",
		description: "Lq 펌프 처리능력 사례9",
		unit: "kg/h",
		min: 0,
	},
	x9_LqTk: {
		name: "탱크 저장능력 사례9",
		description: "Lq 저장탱크 저장능력 사례9",
		unit: "kg",
		min: 0,
	},
	x9_Vap: {
		name: "기화기 처리능력 사례9",
		description: "Lq 기화기 처리능력 사례9",
		unit: "kg/h",
		min: 0,
	},
	x9_YrPrice: {
		name: "연도 사례9",
		description: "연도 사례9",
		unit: "Yr",
		min: 0,
	},
	x9_YrPurch: {
		name: "연도 사례9",
		description: "연도 사례9",
		unit: "Yr",
		min: 0,
	},
	y10_Cp: {
		name: "압축기 구매비용 사례10",
		description: "압축기 구매비용 사례10",
		unit: "백만Won",
		min: 0,
	},
	y10_Disp: {
		name: "충전기 구매비용 사례10",
		description: "Dispenser 구매비용 사례10",
		unit: "백만Won",
		min: 0,
	},
	y10_Elec: {
		name: "급전설비 설치비 사례10",
		description: "급전설비 설치비 사례10",
		unit: "$",
		min: 0,
	},
	y10_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례10",
		description: "압력 48MPa 이상 Bank 구매비용 사례10",
		unit: "백만Won",
		min: 0,
	},
	y10_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례10",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례10",
		unit: "백만Won",
		min: 0,
	},
	y10_LqPp: {
		name: "펌프 구매비용 사례10",
		description: "Lq 펌프 구매비용 사례10",
		unit: "천$",
		min: 0,
	},
	y10_LqTk: {
		name: "탱크 구매비용 사례10",
		description: "Lq 저장탱크 구매비용 사례10",
		unit: "천$",
		min: 0,
	},
	y10_Price: {
		name: "판매비용 사례10",
		description: "판매비용 사례10",
		unit: "Won/kg",
		min: 0,
	},
	y10_Purch: {
		name: "구매비용 사례10",
		description: "구매비용 사례10",
		unit: "Won/kg",
		min: 0,
	},
	y10_Vap: {
		name: "기화기 구매비용 사례10",
		description: "Lq 기화기 구매비용 사례10",
		unit: "천$",
		min: 0,
	},
	y11_Cp: {
		name: "압축기 구매비용 사례11",
		description: "압축기 구매비용 사례11",
		unit: "백만Won",
		min: 0,
	},
	y11_Disp: {
		name: "충전기 구매비용 사례11",
		description: "Dispenser 구매비용 사례11",
		unit: "백만Won",
		min: 0,
	},
	y11_Elec: {
		name: "급전설비 설치비 사례11",
		description: "급전설비 설치비 사례11",
		unit: "$",
		min: 0,
	},
	y11_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례11",
		description: "압력 48MPa 이상 Bank 구매비용 사례11",
		unit: "백만Won",
		min: 0,
	},
	y11_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례11",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례11",
		unit: "백만Won",
		min: 0,
	},
	y11_LqPp: {
		name: "펌프 구매비용 사례11",
		description: "Lq 펌프 구매비용 사례11",
		unit: "천$",
		min: 0,
	},
	y11_LqTk: {
		name: "탱크 구매비용 사례11",
		description: "Lq 저장탱크 구매비용 사례11",
		unit: "천$",
		min: 0,
	},
	y11_Price: {
		name: "판매비용 사례11",
		description: "판매비용 사례11",
		unit: "Won/kg",
		min: 0,
	},
	y11_Purch: {
		name: "구매비용 사례11",
		description: "구매비용 사례11",
		unit: "Won/kg",
		min: 0,
	},
	y11_Vap: {
		name: "기화기 구매비용 사례11",
		description: "Lq 기화기 구매비용 사례11",
		unit: "천$",
		min: 0,
	},
	y12_Cp: {
		name: "압축기 구매비용 사례12",
		description: "압축기 구매비용 사례12",
		unit: "백만Won",
		min: 0,
	},
	y12_Disp: {
		name: "충전기 구매비용 사례12",
		description: "Dispenser 구매비용 사례12",
		unit: "백만Won",
		min: 0,
	},
	y12_Elec: {
		name: "급전설비 설치비 사례12",
		description: "급전설비 설치비 사례12",
		unit: "$",
		min: 0,
	},
	y12_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례12",
		description: "압력 48MPa 이상 Bank 구매비용 사례12",
		unit: "백만Won",
		min: 0,
	},
	y12_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례12",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례12",
		unit: "백만Won",
		min: 0,
	},
	y12_LqPp: {
		name: "펌프 구매비용 사례12",
		description: "Lq 펌프 구매비용 사례12",
		unit: "천$",
		min: 0,
	},
	y12_LqTk: {
		name: "탱크 구매비용 사례12",
		description: "Lq 저장탱크 구매비용 사례12",
		unit: "천$",
		min: 0,
	},
	y12_Price: {
		name: "판매비용 사례12",
		description: "판매비용 사례12",
		unit: "Won/kg",
		min: 0,
	},
	y12_Purch: {
		name: "구매비용 사례12",
		description: "구매비용 사례12",
		unit: "Won/kg",
		min: 0,
	},
	y12_Vap: {
		name: "기화기 구매비용 사례12",
		description: "Lq 기화기 구매비용 사례12",
		unit: "천$",
		min: 0,
	},
	y13_Cp: {
		name: "압축기 구매비용 사례13",
		description: "압축기 구매비용 사례13",
		unit: "백만Won",
		min: 0,
	},
	y13_Disp: {
		name: "충전기 구매비용 사례13",
		description: "Dispenser 구매비용 사례13",
		unit: "백만Won",
		min: 0,
	},
	y13_Elec: {
		name: "급전설비 설치비 사례13",
		description: "급전설비 설치비 사례13",
		unit: "$",
		min: 0,
	},
	y13_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례13",
		description: "압력 48MPa 이상 Bank 구매비용 사례13",
		unit: "백만Won",
		min: 0,
	},
	y13_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례13",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례13",
		unit: "백만Won",
		min: 0,
	},
	y13_LqPp: {
		name: "펌프 구매비용 사례13",
		description: "Lq 펌프 구매비용 사례13",
		unit: "천$",
		min: 0,
	},
	y13_LqTk: {
		name: "탱크 구매비용 사례13",
		description: "Lq 저장탱크 구매비용 사례13",
		unit: "천$",
		min: 0,
	},
	y13_Price: {
		name: "판매비용 사례13",
		description: "판매비용 사례13",
		unit: "Won/kg",
		min: 0,
	},
	y13_Purch: {
		name: "구매비용 사례13",
		description: "구매비용 사례13",
		unit: "Won/kg",
		min: 0,
	},
	y13_Vap: {
		name: "기화기 구매비용 사례13",
		description: "Lq 기화기 구매비용 사례13",
		unit: "천$",
		min: 0,
	},
	y14_Cp: {
		name: "압축기 구매비용 사례14",
		description: "압축기 구매비용 사례14",
		unit: "백만Won",
		min: 0,
	},
	y14_Disp: {
		name: "충전기 구매비용 사례14",
		description: "Dispenser 구매비용 사례14",
		unit: "백만Won",
		min: 0,
	},
	y14_Elec: {
		name: "급전설비 설치비 사례14",
		description: "급전설비 설치비 사례14",
		unit: "$",
		min: 0,
	},
	y14_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례14",
		description: "압력 48MPa 이상 Bank 구매비용 사례14",
		unit: "백만Won",
		min: 0,
	},
	y14_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례14",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례14",
		unit: "백만Won",
		min: 0,
	},
	y14_LqPp: {
		name: "펌프 구매비용 사례14",
		description: "Lq 펌프 구매비용 사례14",
		unit: "천$",
		min: 0,
	},
	y14_LqTk: {
		name: "탱크 구매비용 사례14",
		description: "Lq 저장탱크 구매비용 사례14",
		unit: "천$",
		min: 0,
	},
	y14_Price: {
		name: "판매비용 사례14",
		description: "판매비용 사례14",
		unit: "Won/kg",
		min: 0,
	},
	y14_Purch: {
		name: "구매비용 사례14",
		description: "구매비용 사례14",
		unit: "Won/kg",
		min: 0,
	},
	y14_Vap: {
		name: "기화기 구매비용 사례14",
		description: "Lq 기화기 구매비용 사례14",
		unit: "천$",
		min: 0,
	},
	y15_Cp: {
		name: "압축기 구매비용 사례15",
		description: "압축기 구매비용 사례15",
		unit: "백만Won",
		min: 0,
	},
	y15_Disp: {
		name: "충전기 구매비용 사례15",
		description: "Dispenser 구매비용 사례15",
		unit: "백만Won",
		min: 0,
	},
	y15_Elec: {
		name: "급전설비 설치비 사례15",
		description: "급전설비 설치비 사례15",
		unit: "$",
		min: 0,
	},
	y15_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례15",
		description: "압력 48MPa 이상 Bank 구매비용 사례15",
		unit: "백만Won",
		min: 0,
	},
	y15_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례15",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례15",
		unit: "백만Won",
		min: 0,
	},
	y15_LqPp: {
		name: "펌프 구매비용 사례15",
		description: "Lq 펌프 구매비용 사례15",
		unit: "천$",
		min: 0,
	},
	y15_LqTk: {
		name: "탱크 구매비용 사례15",
		description: "Lq 저장탱크 구매비용 사례15",
		unit: "천$",
		min: 0,
	},
	y15_Price: {
		name: "판매비용 사례15",
		description: "판매비용 사례15",
		unit: "Won/kg",
		min: 0,
	},
	y15_Purch: {
		name: "구매비용 사례15",
		description: "구매비용 사례15",
		unit: "Won/kg",
		min: 0,
	},
	y15_Vap: {
		name: "기화기 구매비용 사례15",
		description: "Lq 기화기 구매비용 사례15",
		unit: "천$",
		min: 0,
	},
	y1_Cp: {
		name: "압축기 구매비용 사례1",
		description: "압축기 구매비용 사례1",
		unit: "백만Won",
		min: 0,
	},
	y1_Disp: {
		name: "충전기 구매비용 사례1",
		description: "Dispenser 구매비용 사례1",
		unit: "백만Won",
		min: 0,
	},
	y1_Elec: {
		name: "급전설비 설치비 사례1",
		description: "급전설비 설치비 사례1",
		unit: "$",
		min: 0,
	},
	y1_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례1",
		description: "압력 48MPa 이상 Bank 구매비용 사례1",
		unit: "백만Won",
		min: 0,
	},
	y1_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례1",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례1",
		unit: "백만Won",
		min: 0,
	},
	y1_LqPp: {
		name: "펌프 구매비용 사례1",
		description: "Lq 펌프 구매비용 사례1",
		unit: "천$",
		min: 0,
	},
	y1_LqTk: {
		name: "탱크 구매비용 사례1",
		description: "Lq 저장탱크 구매비용 사례1",
		unit: "천$",
		min: 0,
	},
	y1_Price: {
		name: "판매비용 사례1",
		description: "판매비용 사례1",
		unit: "Won/kg",
		min: 0,
	},
	y1_Purch: {
		name: "구매비용 사례1",
		description: "구매비용 사례1",
		unit: "Won/kg",
		min: 0,
	},
	y1_Vap: {
		name: "기화기 구매비용 사례1",
		description: "Lq 기화기 구매비용 사례1",
		unit: "천$",
		min: 0,
	},
	y2_Cp: {
		name: "압축기 구매비용 사례2",
		description: "압축기 구매비용 사례2",
		unit: "백만Won",
		min: 0,
	},
	y2_Disp: {
		name: "충전기 구매비용 사례2",
		description: "Dispenser 구매비용 사례2",
		unit: "백만Won",
		min: 0,
	},
	y2_Elec: {
		name: "급전설비 설치비 사례2",
		description: "급전설비 설치비 사례2",
		unit: "$",
		min: 0,
	},
	y2_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례2",
		description: "압력 48MPa 이상 Bank 구매비용 사례2",
		unit: "백만Won",
		min: 0,
	},
	y2_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례2",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례2",
		unit: "백만Won",
		min: 0,
	},
	y2_LqPp: {
		name: "펌프 구매비용 사례2",
		description: "Lq 펌프 구매비용 사례2",
		unit: "천$",
		min: 0,
	},
	y2_LqTk: {
		name: "탱크 구매비용 사례2",
		description: "Lq 저장탱크 구매비용 사례2",
		unit: "천$",
		min: 0,
	},
	y2_Price: {
		name: "판매비용 사례2",
		description: "판매비용 사례2",
		unit: "Won/kg",
		min: 0,
	},
	y2_Purch: {
		name: "구매비용 사례2",
		description: "구매비용 사례2",
		unit: "Won/kg",
		min: 0,
	},
	y2_Vap: {
		name: "기화기 구매비용 사례2",
		description: "Lq 기화기 구매비용 사례2",
		unit: "천$",
		min: 0,
	},
	y3_Cp: {
		name: "압축기 구매비용 사례3",
		description: "압축기 구매비용 사례3",
		unit: "백만Won",
		min: 0,
	},
	y3_Disp: {
		name: "충전기 구매비용 사례3",
		description: "Dispenser 구매비용 사례3",
		unit: "백만Won",
		min: 0,
	},
	y3_Elec: {
		name: "급전설비 설치비 사례3",
		description: "급전설비 설치비 사례3",
		unit: "$",
		min: 0,
	},
	y3_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례3",
		description: "압력 48MPa 이상 Bank 구매비용 사례3",
		unit: "백만Won",
		min: 0,
	},
	y3_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례3",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례3",
		unit: "백만Won",
		min: 0,
	},
	y3_LqPp: {
		name: "펌프 구매비용 사례3",
		description: "Lq 펌프 구매비용 사례3",
		unit: "천$",
		min: 0,
	},
	y3_LqTk: {
		name: "탱크 구매비용 사례3",
		description: "Lq 저장탱크 구매비용 사례3",
		unit: "천$",
		min: 0,
	},
	y3_Price: {
		name: "판매비용 사례3",
		description: "판매비용 사례3",
		unit: "Won/kg",
		min: 0,
	},
	y3_Purch: {
		name: "구매비용 사례3",
		description: "구매비용 사례3",
		unit: "Won/kg",
		min: 0,
	},
	y3_Vap: {
		name: "기화기 구매비용 사례3",
		description: "Lq 기화기 구매비용 사례3",
		unit: "천$",
		min: 0,
	},
	y4_Cp: {
		name: "압축기 구매비용 사례4",
		description: "압축기 구매비용 사례4",
		unit: "백만Won",
		min: 0,
	},
	y4_Disp: {
		name: "충전기 구매비용 사례4",
		description: "Dispenser 구매비용 사례4",
		unit: "백만Won",
		min: 0,
	},
	y4_Elec: {
		name: "급전설비 설치비 사례4",
		description: "급전설비 설치비 사례4",
		unit: "$",
		min: 0,
	},
	y4_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례4",
		description: "압력 48MPa 이상 Bank 구매비용 사례4",
		unit: "백만Won",
		min: 0,
	},
	y4_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례4",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례4",
		unit: "백만Won",
		min: 0,
	},
	y4_LqPp: {
		name: "펌프 구매비용 사례4",
		description: "Lq 펌프 구매비용 사례4",
		unit: "천$",
		min: 0,
	},
	y4_LqTk: {
		name: "탱크 구매비용 사례4",
		description: "Lq 저장탱크 구매비용 사례4",
		unit: "천$",
		min: 0,
	},
	y4_Price: {
		name: "판매비용 사례4",
		description: "판매비용 사례4",
		unit: "Won/kg",
		min: 0,
	},
	y4_Purch: {
		name: "구매비용 사례4",
		description: "구매비용 사례4",
		unit: "Won/kg",
		min: 0,
	},
	y4_Vap: {
		name: "기화기 구매비용 사례4",
		description: "Lq 기화기 구매비용 사례4",
		unit: "천$",
		min: 0,
	},
	y5_Cp: {
		name: "압축기 구매비용 사례5",
		description: "압축기 구매비용 사례5",
		unit: "백만Won",
		min: 0,
	},
	y5_Disp: {
		name: "충전기 구매비용 사례5",
		description: "Dispenser 구매비용 사례5",
		unit: "백만Won",
		min: 0,
	},
	y5_Elec: {
		name: "급전설비 설치비 사례5",
		description: "급전설비 설치비 사례5",
		unit: "$",
		min: 0,
	},
	y5_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례5",
		description: "압력 48MPa 이상 Bank 구매비용 사례5",
		unit: "백만Won",
		min: 0,
	},
	y5_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례5",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례5",
		unit: "백만Won",
		min: 0,
	},
	y5_LqPp: {
		name: "펌프 구매비용 사례5",
		description: "Lq 펌프 구매비용 사례5",
		unit: "천$",
		min: 0,
	},
	y5_LqTk: {
		name: "탱크 구매비용 사례5",
		description: "Lq 저장탱크 구매비용 사례5",
		unit: "천$",
		min: 0,
	},
	y5_Price: {
		name: "판매비용 사례5",
		description: "판매비용 사례5",
		unit: "Won/kg",
		min: 0,
	},
	y5_Purch: {
		name: "구매비용 사례5",
		description: "구매비용 사례5",
		unit: "Won/kg",
		min: 0,
	},
	y5_Vap: {
		name: "기화기 구매비용 사례5",
		description: "Lq 기화기 구매비용 사례5",
		unit: "천$",
		min: 0,
	},
	y6_Cp: {
		name: "압축기 구매비용 사례6",
		description: "압축기 구매비용 사례6",
		unit: "백만Won",
		min: 0,
	},
	y6_Disp: {
		name: "충전기 구매비용 사례6",
		description: "Dispenser 구매비용 사례6",
		unit: "백만Won",
		min: 0,
	},
	y6_Elec: {
		name: "급전설비 설치비 사례6",
		description: "급전설비 설치비 사례6",
		unit: "$",
		min: 0,
	},
	y6_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례6",
		description: "압력 48MPa 이상 Bank 구매비용 사례6",
		unit: "백만Won",
		min: 0,
	},
	y6_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례6",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례6",
		unit: "백만Won",
		min: 0,
	},
	y6_LqPp: {
		name: "펌프 구매비용 사례6",
		description: "Lq 펌프 구매비용 사례6",
		unit: "천$",
		min: 0,
	},
	y6_LqTk: {
		name: "탱크 구매비용 사례6",
		description: "Lq 저장탱크 구매비용 사례6",
		unit: "천$",
		min: 0,
	},
	y6_Price: {
		name: "판매비용 사례6",
		description: "판매비용 사례6",
		unit: "Won/kg",
		min: 0,
	},
	y6_Purch: {
		name: "구매비용 사례6",
		description: "구매비용 사례6",
		unit: "Won/kg",
		min: 0,
	},
	y6_Vap: {
		name: "기화기 구매비용 사례6",
		description: "Lq 기화기 구매비용 사례6",
		unit: "천$",
		min: 0,
	},
	y7_Cp: {
		name: "압축기 구매비용 사례7",
		description: "압축기 구매비용 사례7",
		unit: "백만Won",
		min: 0,
	},
	y7_Disp: {
		name: "충전기 구매비용 사례7",
		description: "Dispenser 구매비용 사례7",
		unit: "백만Won",
		min: 0,
	},
	y7_Elec: {
		name: "급전설비 설치비 사례7",
		description: "급전설비 설치비 사례7",
		unit: "$",
		min: 0,
	},
	y7_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례7",
		description: "압력 48MPa 이상 Bank 구매비용 사례7",
		unit: "백만Won",
		min: 0,
	},
	y7_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례7",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례7",
		unit: "백만Won",
		min: 0,
	},
	y7_LqPp: {
		name: "펌프 구매비용 사례7",
		description: "Lq 펌프 구매비용 사례7",
		unit: "천$",
		min: 0,
	},
	y7_LqTk: {
		name: "탱크 구매비용 사례7",
		description: "Lq 저장탱크 구매비용 사례7",
		unit: "천$",
		min: 0,
	},
	y7_Price: {
		name: "판매비용 사례7",
		description: "판매비용 사례7",
		unit: "Won/kg",
		min: 0,
	},
	y7_Purch: {
		name: "구매비용 사례7",
		description: "구매비용 사례7",
		unit: "Won/kg",
		min: 0,
	},
	y7_Vap: {
		name: "기화기 구매비용 사례7",
		description: "Lq 기화기 구매비용 사례7",
		unit: "천$",
		min: 0,
	},
	y8_Cp: {
		name: "압축기 구매비용 사례8",
		description: "압축기 구매비용 사례8",
		unit: "백만Won",
		min: 0,
	},
	y8_Disp: {
		name: "충전기 구매비용 사례8",
		description: "Dispenser 구매비용 사례8",
		unit: "백만Won",
		min: 0,
	},
	y8_Elec: {
		name: "급전설비 설치비 사례8",
		description: "급전설비 설치비 사례8",
		unit: "$",
		min: 0,
	},
	y8_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례8",
		description: "압력 48MPa 이상 Bank 구매비용 사례8",
		unit: "백만Won",
		min: 0,
	},
	y8_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례8",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례8",
		unit: "백만Won",
		min: 0,
	},
	y8_LqPp: {
		name: "펌프 구매비용 사례8",
		description: "Lq 펌프 구매비용 사례8",
		unit: "천$",
		min: 0,
	},
	y8_LqTk: {
		name: "탱크 구매비용 사례8",
		description: "Lq 저장탱크 구매비용 사례8",
		unit: "천$",
		min: 0,
	},
	y8_Price: {
		name: "판매비용 사례8",
		description: "판매비용 사례8",
		unit: "Won/kg",
		min: 0,
	},
	y8_Purch: {
		name: "구매비용 사례8",
		description: "구매비용 사례8",
		unit: "Won/kg",
		min: 0,
	},
	y8_Vap: {
		name: "기화기 구매비용 사례8",
		description: "Lq 기화기 구매비용 사례8",
		unit: "천$",
		min: 0,
	},
	y9_Cp: {
		name: "압축기 구매비용 사례9",
		description: "압축기 구매비용 사례9",
		unit: "백만Won",
		min: 0,
	},
	y9_Disp: {
		name: "충전기 구매비용 사례9",
		description: "Dispenser 구매비용 사례9",
		unit: "백만Won",
		min: 0,
	},
	y9_Elec: {
		name: "급전설비 설치비 사례9",
		description: "급전설비 설치비 사례9",
		unit: "$",
		min: 0,
	},
	y9_HBk: {
		name: "48MPa 이상 뱅크 구매비용 사례9",
		description: "압력 48MPa 이상 Bank 구매비용 사례9",
		unit: "백만Won",
		min: 0,
	},
	y9_LBk: {
		name: "48MPa 미만 뱅크 및 버퍼 구매비용 사례9",
		description: "압력 48MPa 미만 Bank 및 Buffer구매비용 사례9",
		unit: "백만Won",
		min: 0,
	},
	y9_LqPp: {
		name: "펌프 구매비용 사례9",
		description: "Lq 펌프 구매비용 사례9",
		unit: "천$",
		min: 0,
	},
	y9_LqTk: {
		name: "탱크 구매비용 사례9",
		description: "Lq 저장탱크 구매비용 사례9",
		unit: "천$",
		min: 0,
	},
	y9_Price: {
		name: "판매비용 사례9",
		description: "판매비용 사례9",
		unit: "Won/kg",
		min: 0,
	},
	y9_Purch: {
		name: "구매비용 사례9",
		description: "구매비용 사례9",
		unit: "Won/kg",
		min: 0,
	},
	y9_Vap: {
		name: "기화기 구매비용 사례9",
		description: "Lq 기화기 구매비용 사례9",
		unit: "천$",
		min: 0,
	},
};
