const a = [
  {
    id: "SFC4050",
    name: "시나리오 - 4050",
    sfcName: "4050",
    type: "scenario",
    children: [{ ...DEVICES.Disp1 }, { ...DEVICES.TkVe1 }],
    src: "diagram13.png",
  },
  {
    id: "SFC4110",
    name: "시나리오 - 4110",
    sfcName: "4110",
    type: "scenario",
    children: [{ ...DEVICES.LBk }, { ...DEVICES.PSV_LBk }],
    src: "diagram14.png",
  },
  {
    id: "SFC4120",
    name: "시나리오 - 4120",
    sfcName: "4120",
    type: "scenario",
    children: [{ ...DEVICES.MBk }, { ...DEVICES.PSV_MBk }],
    src: "diagram15.png",
  },
  {
    id: "SFC4130",
    name: "시나리오 - 4130",
    sfcName: "4130",
    type: "scenario",
    children: [{ ...DEVICES.HBk }, { ...DEVICES.PSV_HBk }],
    src: "diagram16.png",
  },
  {
    id: "SFC4500",
    name: "시나리오 - 4500",
    sfcName: "4500",
    type: "scenario",
    children: [{ ...DEVICES.Lq_Tk }],
    src: "diagram17.png",
  },
  {
    id: "SFC5110",
    name: "시나리오 - 5110",
    sfcName: "5110",
    type: "scenario",
    children: [
      { ...DEVICES.Disp1 },
      { ...DEVICES.TkVe1 },
      { ...DEVICES.What_if },
    ],
    src: "diagram18.png",
  },
];
